/**
 * CATÁLOGO BLIZZCOOL — fichero de datos
 * ---------------------------------------------------
 * Precios: columna PVP de la tarifa oficial (TARIFA_BLIZZCOOL_NETOS_Y_REVENDEDORES.xlsx),
 * siempre SIN IVA. El sitio calcula el 21% de IVA con el interruptor de la cabecera.
 *
 * Cómo alimentar este fichero:
 * - imagen: ruta a la foto principal del equipo (ej. "img/ac-1900-1.jpg"). Déjalo en null si aún no hay foto.
 * - imagenes: opcional, array con fotos adicionales para la galería de la ficha de producto
 *   (ej. ["img/ac-1900-1-2.jpg", "img/ac-1900-1-3.jpg"]). No hace falta repetir la de "imagen".
 * - pvp: precio de venta al público SIN IVA (número). Es el precio de referencia de la tarifa.
 * - specs: lista de { label, value } — lo que sale en la ficha técnica.
 * - sageTools / gid: códigos internos de la tarifa, se muestran como referencia en la ficha.
 * - No borres ningún campo aunque esté vacío: usa null o "" para no romper la página.
 * - Para añadir un producto nuevo, copia un bloque entero y cambia el "id" (debe ser único, sin espacios).
 */

const CATEGORIAS = [
  { id: "aire-acondicionado", nombre: "Aire acondicionado industrial portátil", nombreEn: "Portable industrial air conditioning" },
  { id: "enfriadores-evaporativos", nombre: "Enfriadores evaporativos industriales", nombreEn: "Industrial evaporative coolers" },
  { id: "nebulizadores", nombre: "Nebulizadores industriales", nombreEn: "Industrial misting fans" },
  { id: "ventiladores-techo", nombre: "Ventiladores industriales de techo", nombreEn: "Industrial ceiling fans" },
  { id: "ventiladores-portatiles", nombre: "Ventiladores industriales portátiles", nombreEn: "Portable industrial fans" },
  { id: "ventiladores-pared", nombre: "Ventiladores industriales de pared", nombreEn: "Industrial wall fans" },
  { id: "recambios", nombre: "Recambios y post-venta", nombreEn: "Spare parts & after-sales" },
];

const PRODUCTOS = [
  // ---------- AIRE ACONDICIONADO INDUSTRIAL PORTÁTIL ----------
  {
    id: "ac-1900-1",
    categoria: "aire-acondicionado",
    nombre: "AC-1900/1",
    resumen: "Spot cooler compacto para espacios medianos, oficinas y locales sin obra.",
    resumenEn: "Compact spot cooler for medium-sized spaces, offices and premises with no building work.",
    imagen: "img/ac-19001/ac-1900-1.png",
    imagenes: ["img/ac-19001/ac-1900-1-2.png", "img/ac-19001/ac-1900-1-3.png", "img/ac-19001/ac-1900-1-4.png", "img/ac-19001/ac-1900-1-5.png"],
    pvp: 695,
    sageTools: "1030001",
    gid: "5252.5",
    destacado: true,
    descripcion: "Aire acondicionado portátil por compresor, listo para enfriar con un simple enchufe estándar y un tubo de evacuación al exterior. Pensado para locales comerciales, oficinas en alquiler o como equipo de emergencia cuando falla un sistema fijo.",
    descripcionEn: "Portable compressor air conditioner, ready to cool with a standard plug and an exhaust duct to the outside. Designed for commercial premises, rented offices, or as a backup unit when a fixed system fails.",
    specs: [
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Capacidad frigorífica", value: "2,0 kW (2.000 frigorías)" },
      { label: "Potencia nominal", value: "700 W" },
      { label: "Corriente nominal", value: "3,2 A" },
      { label: "Caudal de aire", value: "230 m³/h" },
      { label: "Refrigerante", value: "R290 (180 g)" },
      { label: "Ambiente de servicio", value: "20–43 °C" },
      { label: "Nivel sonoro", value: "52 dB(A)" },
      { label: "Dimensiones", value: "465 × 287 × 586 mm" },
      { label: "Peso neto / bruto", value: "25,5 kg / 28,3 kg" },
      { label: "Superficie recomendada", value: "Hasta 190 m²" },
      { label: "Depósito de agua", value: "3 L" },
      { label: "Presión máx. aspiración / descarga", value: "10 / 25 bares" },
    ],
    specsEn: [
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Cooling capacity", value: "2,0 kW (2.000 frigorías)" },
      { label: "Rated power", value: "700 W" },
      { label: "Rated current", value: "3,2 A" },
      { label: "Air flow", value: "230 m³/h" },
      { label: "Refrigerant", value: "R290 (180 g)" },
      { label: "Operating range", value: "20–43 °C" },
      { label: "Noise level", value: "52 dB(A)" },
      { label: "Dimensions", value: "465 × 287 × 586 mm" },
      { label: "Net / gross weight", value: "25,5 kg / 28,3 kg" },
      { label: "Recommended area", value: "Hasta 190 m²" },
      { label: "Water tank", value: "3 L" },
      { label: "Max. suction / discharge pressure", value: "10 / 25 bar" },
    ],
    aplicaciones: ["Locales comerciales y oficinas en alquiler", "Salas de servidores pequeñas", "Equipo de emergencia ante avería de climatización fija", "Eventos y ferias", "Vestuarios y casetas deportivas"],
    aplicacionesEn: ["Rented commercial units and offices", "Small server rooms", "Emergency backup for fixed HVAC failure", "Events and trade fairs", "Changing rooms and sports huts"],
    variantes: null,
  },
  {
    id: "ac-2700-1",
    categoria: "aire-acondicionado",
    nombre: "AC-2700/1",
    resumen: "Spot cooler intermedio para talleres y locales de tamaño medio.",
    resumenEn: "Mid-range spot cooler for workshops and medium-sized premises.",
    imagen: "img/ac-27001/ac-2700-1.png",
    imagenes: ["img/ac-27001/ac-2700-1-2.png", "img/ac-27001/ac-2700-1-3.png", "img/ac-27001/ac-2700-1-4.png"],
    pvp: 890,
    sageTools: "1030002",
    gid: "5252.1",
    destacado: false,
    descripcion: "Segundo escalón de la gama de spot coolers Blizzcool, entre el AC-1900/1 y el AC-3500/2. Refrigeración por compresor, portátil y sin necesidad de instalación fija. Es también la elección habitual para salas de servidores por su bajo consumo.",
    descripcionEn: "The second step in the Blizzcool spot cooler range, between the AC-1900/1 and the AC-3500/2. Compressor cooling, portable and with no need for fixed installation. Also the usual choice for server rooms thanks to its low consumption.",
    specs: [
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Capacidad frigorífica", value: "2.700 frigorías" },
      { label: "Caudal de aire", value: "400 m³/h" },
      { label: "Potencia nominal", value: "950 W" },
      { label: "Corriente nominal", value: "4,2 A" },
      { label: "Ambiente de servicio", value: "18–45 °C" },
      { label: "Refrigerante", value: "R290 (250 g)" },
      { label: "Nivel sonoro", value: "55 dB(A)" },
      { label: "Dimensiones", value: "405 × 430 × 855 mm" },
      { label: "Peso neto", value: "42 kg" },
      { label: "Depósito de agua", value: "5 L" },
      { label: "Presión máx. aspiración / descarga", value: "10 / 25 bares" },
    ],
    specsEn: [
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Cooling capacity", value: "2.700 frigorías" },
      { label: "Air flow", value: "400 m³/h" },
      { label: "Rated power", value: "950 W" },
      { label: "Rated current", value: "4,2 A" },
      { label: "Operating range", value: "18–45 °C" },
      { label: "Refrigerant", value: "R290 (250 g)" },
      { label: "Noise level", value: "55 dB(A)" },
      { label: "Dimensions", value: "405 × 430 × 855 mm" },
      { label: "Net weight", value: "42 kg" },
      { label: "Water tank", value: "5 L" },
      { label: "Max. suction / discharge pressure", value: "10 / 25 bar" },
    ],
    aplicaciones: ["Talleres y locales comerciales medianos", "Salas de servidores y racks electrónicos", "Eventos y ferias", "Vestuarios y salas deportivas"],
    aplicacionesEn: ["Workshops and medium-sized commercial units", "Server rooms and electronic racks", "Events and trade fairs", "Changing rooms and sports rooms"],
    variantes: null,
  },
  {
    id: "ac-3500-2",
    categoria: "aire-acondicionado",
    nombre: "AC-3500/2",
    resumen: "3.500 frigorías para talleres, almacenes y fábricas de tamaño medio.",
    resumenEn: "3,500 frigories for workshops, warehouses and mid-sized factories.",
    imagen: "img/ac-35002/ac-3500-2.png",
    imagenes: ["img/ac-35002/ac-3500-2-2.png", "img/ac-35002/ac-3500-2-3.png", "img/ac-35002/ac-3500-2-4.png", "img/ac-35002/ac-3500-2-5.png"],
    pvp: 1165,
    sageTools: "1030003",
    gid: "5252.2",
    destacado: true,
    descripcion: "Sistema de refrigeración por compresor de alto rendimiento y bajo consumo, diseñado para trabajar de forma continua en entornos exigentes. Portátil, con ruedas y sin necesidad de instalación fija.",
    descripcionEn: "High-performance, low-consumption compressor cooling system, designed to run continuously in demanding environments. Portable, on wheels, with no need for fixed installation.",
    specs: [
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Capacidad frigorífica", value: "3.500 frigorías" },
      { label: "Caudal de aire", value: "600 m³/h" },
      { label: "Potencia nominal", value: "1.400 W" },
      { label: "Corriente nominal", value: "6,2 A" },
      { label: "Ambiente de servicio", value: "18–45 °C" },
      { label: "Refrigerante", value: "R290 (300 g)" },
      { label: "Nivel sonoro", value: "57 dB(A)" },
      { label: "Dimensiones", value: "430 × 493 × 944 mm" },
      { label: "Peso neto", value: "49 kg" },
      { label: "Depósito de agua", value: "7 L" },
      { label: "Presión máx. aspiración / descarga", value: "10 / 25 bares" },
    ],
    specsEn: [
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Cooling capacity", value: "3.500 frigorías" },
      { label: "Air flow", value: "600 m³/h" },
      { label: "Rated power", value: "1.400 W" },
      { label: "Rated current", value: "6,2 A" },
      { label: "Operating range", value: "18–45 °C" },
      { label: "Refrigerant", value: "R290 (300 g)" },
      { label: "Noise level", value: "57 dB(A)" },
      { label: "Dimensions", value: "430 × 493 × 944 mm" },
      { label: "Net weight", value: "49 kg" },
      { label: "Water tank", value: "7 L" },
      { label: "Max. suction / discharge pressure", value: "10 / 25 bar" },
    ],
    aplicaciones: ["Talleres y almacenes", "Fábricas", "Eventos, ferias y exposiciones", "Salas y oficinas de instalaciones deportivas"],
    aplicacionesEn: ["Workshops and warehouses", "Factories", "Events, trade fairs and exhibitions", "Sports facility rooms and offices"],
    variantes: null,
  },
  {
    id: "ac-5300-3",
    categoria: "aire-acondicionado",
    nombre: "AC-5300/3",
    resumen: "La referencia de mayor capacidad de la gama, para grandes superficies.",
    resumenEn: "The highest-capacity unit in the range, for large floor areas.",
    imagen: "img/ac-53003/ac-5300-3.png",
    imagenes: ["img/ac-53003/ac-5300-3-2.png", "img/ac-53003/ac-5300-3-3.png", "img/ac-53003/ac-5300-3-4.png", "img/ac-53003/ac-5300-3-5.png"],
    pvp: 1990,
    sageTools: "1030004",
    gid: "5252.3",
    destacado: false,
    descripcion: "El modelo de mayores prestaciones de la gama de spot coolers Blizzcool. Refrigeración por compresor de alto rendimiento para naves y locales de gran superficie, operativo el mismo día sin obra ni permisos.",
    descripcionEn: "The top-performing model in the Blizzcool spot cooler range. High-performance compressor cooling for large industrial buildings and premises, operational the same day with no building work or permits.",
    specs: [
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Capacidad frigorífica", value: "5.300 frigorías" },
      { label: "Caudal de aire", value: "800 m³/h" },
      { label: "Potencia nominal", value: "2.200 W" },
      { label: "Corriente nominal", value: "10,0 A" },
      { label: "Ambiente de servicio", value: "18–45 °C" },
      { label: "Refrigerante", value: "R1234yf (950 g)" },
      { label: "Nivel sonoro", value: "65 dB(A)" },
      { label: "Dimensiones", value: "652 × 560 × 1.135 mm" },
      { label: "Peso neto", value: "95 kg" },
      { label: "Depósito de agua", value: "25 L" },
      { label: "Presión máx. aspiración / descarga", value: "10 / 25 bares" },
    ],
    specsEn: [
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Cooling capacity", value: "5.300 frigorías" },
      { label: "Air flow", value: "800 m³/h" },
      { label: "Rated power", value: "2.200 W" },
      { label: "Rated current", value: "10,0 A" },
      { label: "Operating range", value: "18–45 °C" },
      { label: "Refrigerant", value: "R1234yf (950 g)" },
      { label: "Noise level", value: "65 dB(A)" },
      { label: "Dimensions", value: "652 × 560 × 1,135 mm" },
      { label: "Net weight", value: "95 kg" },
      { label: "Water tank", value: "25 L" },
      { label: "Max. suction / discharge pressure", value: "10 / 25 bar" },
    ],
    aplicaciones: ["Naves industriales de gran superficie", "Salas de servidores y centros de datos", "Locales comerciales grandes", "Pabellones y polideportivos"],
    aplicacionesEn: ["Large-footprint industrial buildings", "Server rooms and data centres", "Large commercial premises", "Sports halls and pavilions"],
    variantes: null,
  },
  // ---------- ENFRIADORES EVAPORATIVOS INDUSTRIALES ----------
  {
    id: "bc-200",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 200",
    resumen: "Enfriador evaporativo de entrada de gama, para espacios medianos.",
    resumenEn: "Entry-level evaporative cooler for medium-sized spaces.",
    imagen: "img/bc200/bc-200.png",
    imagenes: [
      { src: "img/bc200/bc-200-lateral.jpg", fit: "contain" },
      { src: "img/bc200/bc-200-closeup.png", fit: "contain" },
      { src: "img/bc200/bc-200-detalle-1.png", fit: "contain" },
      { src: "img/bc200/bc-200-detalle-2.png", fit: "contain" },
      { src: "img/bc200/bc-200-detalle-3.png", fit: "contain" },
      { src: "img/bc200/bc-200-medidas.png", fit: "contain" },
      { src: "img/bc200/tamano-todos.png", fit: "contain" },
    ],
    pvp: 1540,
    sageTools: "1010001",
    gid: "5176.7",
    destacado: false,
    descripcion: "Equipo de climatización por evaporación de agua: aspira aire caliente, lo hace pasar por paneles húmedos y lo devuelve más frío, sin gases refrigerantes ni compresor. Consumo eléctrico muy inferior al de un aire acondicionado equivalente.",
    descripcionEn: "Water-evaporation climate control unit: draws in hot air, passes it through wet pads and returns it cooler, with no refrigerant gases or compressor. Electricity consumption far lower than an equivalent air conditioner.",
    specs: [
      { label: "Tipo", value: "Enfriador evaporativo" },
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Potencia del motor", value: "630 W" },
      { label: "Flujo de aire máximo", value: "150 m³/min" },
      { label: "Área de enfriamiento", value: "Hasta 200 m²" },
      { label: "Capacidad del depósito", value: "72 L" },
      { label: "Diámetro del ventilador", value: "460 mm" },
      { label: "Dimensiones", value: "920 × 580 × 1.180 mm" },
      { label: "Peso en vacío", value: "54 kg" },
      { label: "Nivel sonoro", value: "70–90 dB" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    specsEn: [
      { label: "Type", value: "Evaporative cooler" },
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Motor power", value: "630 W" },
      { label: "Max. air flow", value: "150 m³/min" },
      { label: "Cooling area", value: "Up to 200 m²" },
      { label: "Tank capacity", value: "72 L" },
      { label: "Fan diameter", value: "460 mm" },
      { label: "Dimensions", value: "920 × 580 × 1,180 mm" },
      { label: "Empty weight", value: "54 kg" },
      { label: "Noise level", value: "70–90 dB" },
      { label: "Refrigerant", value: "No gases — water and air only" },
      { label: "Recommended climate", value: "Dry — relative humidity below 60%" },
    ],
    aplicaciones: ["Talleres y almacenes medianos", "Locales comerciales", "Boxes de CrossFit y salas de boxeo", "Vestuarios deportivos"],
    aplicacionesEn: ["Medium-sized workshops and warehouses", "Commercial premises", "CrossFit boxes and boxing gyms", "Sports changing rooms"],
    variantes: null,
  },
  {
    id: "bc-290",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 290",
    resumen: "Enfriador evaporativo de gama media, mayor caudal que el BC 200.",
    resumenEn: "Mid-range evaporative cooler, higher airflow than the BC 200.",
    imagen: "img/bc290/bc-290.png",
    imagenes: [
      { src: "img/bc290/bc-290-lateral.png", fit: "contain" },
      { src: "img/bc290/bc-290-closeup.png", fit: "contain" },
      { src: "img/bc290/bc-290-detalle-1.png", fit: "contain" },
      { src: "img/bc290/bc-290-detalle-2.png", fit: "contain" },
      { src: "img/bc290/bc-290-detalle-3.png", fit: "contain" },
      { src: "img/bc290/bc-290-medidas.png", fit: "contain" },
      { src: "img/bc290/tamano-todos.png", fit: "contain" },
    ],
    pvp: 1815,
    sageTools: "1010002",
    gid: "5176.2",
    destacado: false,
    descripcion: "Equipo de climatización por evaporación de agua, un escalón por encima del BC 200 en caudal de aire. Sin gases refrigerantes ni compresor, con un coste operativo muy inferior al del aire acondicionado tradicional.",
    descripcionEn: "Water-evaporation climate control unit, one step above the BC 200 in airflow. No refrigerant gases or compressor, with running costs far lower than traditional air conditioning.",
    specs: [
      { label: "Tipo", value: "Enfriador evaporativo" },
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Potencia del motor", value: "530 W" },
      { label: "Flujo de aire máximo", value: "220 m³/min" },
      { label: "Área de enfriamiento", value: "Hasta 290 m²" },
      { label: "Capacidad del depósito", value: "110 L" },
      { label: "Diámetro del ventilador", value: "600 mm" },
      { label: "Dimensiones", value: "1.140 × 650 × 1.370 mm" },
      { label: "Peso en vacío", value: "97 kg" },
      { label: "Nivel sonoro", value: "70–90 dB" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    specsEn: [
      { label: "Type", value: "Evaporative cooler" },
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Motor power", value: "530 W" },
      { label: "Max. air flow", value: "220 m³/min" },
      { label: "Cooling area", value: "Up to 290 m²" },
      { label: "Tank capacity", value: "110 L" },
      { label: "Fan diameter", value: "600 mm" },
      { label: "Dimensions", value: "1,140 × 650 × 1,370 mm" },
      { label: "Empty weight", value: "97 kg" },
      { label: "Noise level", value: "70–90 dB" },
      { label: "Refrigerant", value: "No gases — water and air only" },
      { label: "Recommended climate", value: "Dry — relative humidity below 60%" },
    ],
    aplicaciones: ["Naves y talleres", "Almacenes y centros logísticos", "Gimnasios y salas de fitness", "Terrazas de hostelería"],
    aplicacionesEn: ["Industrial buildings and workshops", "Warehouses and logistics centres", "Gyms and fitness studios", "Hospitality terraces"],
    variantes: null,
  },
  {
    id: "bc-395",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 395",
    resumen: "Enfriador evaporativo de gran caudal para naves y espacios amplios.",
    resumenEn: "High-airflow evaporative cooler for industrial buildings and large spaces.",
    imagen: "img/bc395/bc-395.png",
    imagenes: [
      { src: "img/bc395/bc-395-lateral.png", fit: "contain" },
      { src: "img/bc395/bc-395-detalle-1.png", fit: "contain" },
      { src: "img/bc395/bc-395-detalle-2.png", fit: "contain" },
      { src: "img/bc395/bc-395-detalle-3.png", fit: "contain" },
      { src: "img/bc395/bc-395-medidas.png", fit: "contain" },
      { src: "img/bc395/tamano-todos.png", fit: "contain" },
    ],
    pvp: 2189,
    sageTools: "1010003",
    gid: "5176.3",
    destacado: true,
    descripcion: "Equipo de climatización por evaporación de agua: aspira aire caliente, lo hace pasar por paneles húmedos y lo devuelve hasta 15 °C más frío, sin gases refrigerantes ni compresor. Consumo eléctrico muy inferior al de un aire acondicionado equivalente.",
    descripcionEn: "Water-evaporation climate control unit: draws in hot air, passes it through wet pads and returns it up to 15 °C cooler, with no refrigerant gases or compressor. Electricity consumption far lower than an equivalent air conditioner.",
    specs: [
      { label: "Caudal de aire", value: "Hasta 345 m³/min" },
      { label: "Reducción de temperatura", value: "Entre 12 y 15 °C en condiciones óptimas" },
      { label: "Consumo estimado", value: "0,5–3 kW/h según modelo" },
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Potencia del motor", value: "860 W" },
      { label: "Área de enfriamiento", value: "Hasta 395 m²" },
      { label: "Capacidad del depósito", value: "126 L" },
      { label: "Diámetro del ventilador", value: "900 mm" },
      { label: "Dimensiones", value: "1.510 × 780 × 1.890 mm" },
      { label: "Peso en vacío", value: "126 kg" },
      { label: "Nivel sonoro", value: "70–90 dB" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Extra", value: "Sistema anti-bacterias integrado" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    specsEn: [
      { label: "Air flow", value: "Hasta 345 m³/min" },
      { label: "Temperature drop", value: "Entre 12 y 15 °C en condiciones óptimas" },
      { label: "Estimated consumption", value: "0,5–3 kW/h según modelo" },
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Motor power", value: "860 W" },
      { label: "Cooling area", value: "Up to 395 m²" },
      { label: "Tank capacity", value: "126 L" },
      { label: "Fan diameter", value: "900 mm" },
      { label: "Dimensions", value: "1,510 × 780 × 1,890 mm" },
      { label: "Empty weight", value: "126 kg" },
      { label: "Noise level", value: "70–90 dB" },
      { label: "Refrigerant", value: "No gases — water and air only" },
      { label: "Extra", value: "Integrated anti-bacterial system" },
      { label: "Recommended climate", value: "Dry — relative humidity below 60%" },
    ],
    aplicaciones: ["Naves industriales y de producción", "Talleres mecánicos y de carrocería", "Pabellones deportivos y polideportivos", "Campos de fútbol y pistas de atletismo", "Terrazas de hostelería"],
    aplicacionesEn: ["Industrial and production buildings", "Mechanical and bodywork workshops", "Sports halls and pavilions", "Football pitches and athletics tracks", "Hospitality terraces"],
    variantes: null,
  },
  // ---------- NEBULIZADORES INDUSTRIALES ----------
  {
    id: "bsm-160l",
    categoria: "nebulizadores",
    nombre: "BSM160L",
    resumen: "Nebulizador de alto caudal con depósito de 160 litros para jornadas completas.",
    resumenEn: "High-flow misting fan with a 160-litre tank for full working days.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/Front-BSM160.avif",
    imagenes: ["img/bsm-160l/bsm-160l-atletismo.jpg", "img/bsm-160l/bsm-160l-futbol.jpg", "img/bsm-160l/bsm-160l-descanso.jpg", "img/bsm-160l/bsm-160l-fitness.jpg"],
    pvp: 2490.35,
    sageTools: "1040001",
    gid: "5176.24",
    destacado: true,
    descripcion: "Sistema de nebulización de gota fina (por debajo de 10 micras) que garantiza evaporación completa sin mojar personas ni superficies. Funciona con un simple enchufe estándar, sin instalación eléctrica específica.",
    descripcionEn: "Fine-droplet misting system (under 10 microns) that guarantees full evaporation without wetting people or surfaces. Runs off a standard plug socket, with no dedicated electrical installation.",
    specs: [
      { label: "Capacidad de depósito", value: "160 L" },
      { label: "Tamaño de gota", value: "Menos de 10 micras" },
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Potencia", value: "796 W" },
      { label: "Volumen de aire", value: "6.957 CFM" },
      { label: "Salida de aire", value: "Ø 66 cm" },
      { label: "Área de enfriamiento", value: "Hasta 250 m²" },
      { label: "Consumo de agua", value: "6 L/h" },
      { label: "Dimensiones", value: "1.126 × 760 × 1.550 mm" },
      { label: "Peso", value: "74 kg" },
      { label: "Rendimiento óptimo", value: "Humedad relativa por debajo del 70–75%" },
    ],
    specsEn: [
      { label: "Tank capacity", value: "160 L" },
      { label: "Droplet size", value: "Menos de 10 micras" },
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Power", value: "796 W" },
      { label: "Air volume", value: "6,957 CFM" },
      { label: "Air outlet", value: "Ø 66 cm" },
      { label: "Cooling area", value: "Up to 250 m²" },
      { label: "Water consumption", value: "6 L/h" },
      { label: "Dimensions", value: "1,126 × 760 × 1,550 mm" },
      { label: "Weight", value: "74 kg" },
      { label: "Optimal performance", value: "Humedad relativa por debajo del 70–75%" },
    ],
    aplicaciones: ["Naves industriales y logística", "Hostelería y terrazas", "Eventos deportivos y culturales"],
    aplicacionesEn: ["Industrial and logistics buildings", "Hospitality venues and terraces", "Sports and cultural events"],
    variantes: null,
  },
  {
    id: "bsm-380l",
    categoria: "nebulizadores",
    nombre: "BSM380L",
    resumen: "Máxima autonomía de la gama: depósito de 380 litros para eventos y grandes espacios.",
    resumenEn: "Maximum runtime in the range: 380-litre tank for events and large spaces.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/Front-BSM380.avif",
    imagenes: ["img/bsm-380l/bsm-380l-caso-1.jpg", "img/bsm-380l/bsm-380l-caso-2.jpg", "img/bsm-380l/bsm-380l-caso-3.jpg", "img/bsm-380l/bsm-380l-caso-4.jpg"],
    pvp: 2992.28,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor depósito de la gama de nebulizadores industriales Blizzcool, pensada para jornadas o eventos completos sin recargas, cubriendo superficies de hasta 250 m² por equipo.",
    descripcionEn: "The largest-tank model in the Blizzcool misting fan range, designed for full working days or events with no refills, covering up to 250 m² per unit.",
    specs: [
      { label: "Capacidad de depósito", value: "380 L" },
      { label: "Cobertura", value: "Hasta 250 m² por equipo" },
      { label: "Tamaño de gota", value: "Menos de 10 micras" },
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Potencia", value: "602 W" },
      { label: "Volumen de aire", value: "7.026 CFM" },
      { label: "Salida de aire", value: "Ø 66 cm" },
      { label: "Consumo de agua", value: "6 L/h" },
      { label: "Dimensiones", value: "1.190 × 952 × 1.632 mm" },
      { label: "Peso", value: "82 kg" },
    ],
    specsEn: [
      { label: "Tank capacity", value: "380 L" },
      { label: "Coverage", value: "Hasta 250 m² por equipo" },
      { label: "Droplet size", value: "Menos de 10 micras" },
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Power", value: "602 W" },
      { label: "Air volume", value: "7,026 CFM" },
      { label: "Air outlet", value: "Ø 66 cm" },
      { label: "Water consumption", value: "6 L/h" },
      { label: "Dimensions", value: "1,190 × 952 × 1,632 mm" },
      { label: "Weight", value: "82 kg" },
    ],
    aplicaciones: ["Pabellones y campus deportivos sin climatización centralizada", "Eventos y ferias exteriores", "Zonas VIP y áreas de calentamiento"],
    aplicacionesEn: ["Sports halls and campuses without central HVAC", "Outdoor events and trade fairs", "VIP areas and warm-up zones"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES DE TECHO ----------
  {
    id: "fam240",
    categoria: "ventiladores-techo",
    nombre: "BW FAM240 · Ø2400 mm",
    resumen: "Ventilador de techo de gran diámetro, entrada de gama de la serie FAM.",
    resumenEn: "Large-diameter ceiling fan, entry point of the FAM series.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-de-Techo-BUENA-WEB-1024x1024.avif",
    imagenes: ["img/fam-240/fam240-caso-1.jpg", "img/fam-240/fam240-caso-2.jpg", "img/fam-240/fam240-caso-3.jpg", "img/fam-240/fam240-caso-4.jpg"],
    pvp: 1090,
    sageTools: "1021001",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad. Mueve grandes volúmenes de aire con un consumo mucho menor que un equipo de climatización de potencia equivalente, sin necesidad de enfriar todo el volumen de la nave.",
    descripcionEn: "High-volume, low-speed ceiling fan. Moves large volumes of air with far lower consumption than an equivalent-power HVAC unit, without needing to cool the whole volume of the building.",
    specs: [
      { label: "Diámetro", value: "2.400 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
      { label: "Caudal de aire", value: "3.300 m³/min" },
      { label: "Área de trabajo", value: "Hasta 100 m²" },
      { label: "Potencia", value: "0,30 kW" },
      { label: "Velocidad máxima", value: "140 RPM" },
      { label: "Alimentación", value: "220–240 / 380–460 V · 50/60 Hz" },
    ],
    specsEn: [
      { label: "Diameter", value: "2.400 mm" },
      { label: "Type", value: "Ceiling, high volume / low speed (HVLS)" },
      { label: "Air flow", value: "3,300 m³/min" },
      { label: "Working area", value: "Up to 100 m²" },
      { label: "Power", value: "0.30 kW" },
      { label: "Max. rotation speed", value: "140 RPM" },
      { label: "Power supply", value: "220–240 / 380–460 V · 50/60 Hz" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Complemento de climatización existente", "Pabellones deportivos"],
    aplicacionesEn: ["High-ceiling industrial buildings", "Complement to existing HVAC", "Sports halls"],
    variantes: null,
  },
  {
    id: "fam300",
    categoria: "ventiladores-techo",
    nombre: "BW FAM300 · Ø3000 mm",
    resumen: "Ventilador de techo de la serie FAM, un escalón por encima del FAM240.",
    resumenEn: "Ceiling fan from the FAM series, one step up from the FAM240.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-de-Techo-BUENA-WEB-1024x1024.avif",
    imagenes: ["img/fam-300/fam300-caso-1.jpg", "img/fam-300/fam300-caso-2.jpg", "img/fam-300/fam300-caso-3.jpg", "img/fam-300/fam300-caso-4.jpg"],
    pvp: 1120,
    sageTools: "1021002",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad, con mayor diámetro que el FAM240 para cubrir superficies más amplias.",
    descripcionEn: "High-volume, low-speed ceiling fan, with a larger diameter than the FAM240 to cover wider areas.",
    specs: [
      { label: "Diámetro", value: "3.000 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
      { label: "Caudal de aire", value: "4.000 m³/min" },
      { label: "Área de trabajo", value: "Hasta 150 m²" },
      { label: "Potencia", value: "0,37 kW" },
      { label: "Velocidad máxima", value: "120 RPM" },
      { label: "Alimentación", value: "220–240 / 380–460 V · 50/60 Hz" },
    ],
    specsEn: [
      { label: "Diameter", value: "3.000 mm" },
      { label: "Type", value: "Ceiling, high volume / low speed (HVLS)" },
      { label: "Air flow", value: "4,000 m³/min" },
      { label: "Working area", value: "Up to 150 m²" },
      { label: "Power", value: "0.37 kW" },
      { label: "Max. rotation speed", value: "120 RPM" },
      { label: "Power supply", value: "220–240 / 380–460 V · 50/60 Hz" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Complemento de climatización existente", "Pabellones deportivos"],
    aplicacionesEn: ["High-ceiling industrial buildings", "Complement to existing HVAC", "Sports halls"],
    variantes: null,
  },
  {
    id: "fam370",
    categoria: "ventiladores-techo",
    nombre: "BW FAM370 · Ø3700 mm",
    resumen: "Ventilador de techo de gran diámetro para naves amplias.",
    resumenEn: "Large-diameter ceiling fan for spacious industrial buildings.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-de-Techo-BUENA-WEB-1024x1024.avif",
    imagenes: ["img/fam-370/fam370-caso-1.jpg", "img/fam-370/fam370-caso-2.jpg", "img/fam-370/fam370-caso-3.jpg", "img/fam-370/fam370-caso-4.jpg"],
    pvp: 1190,
    sageTools: "1021003",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad, pensado para espacios de mayor superficie que los modelos FAM240 y FAM300.",
    descripcionEn: "High-volume, low-speed ceiling fan, designed for larger-floor-area buildings than the FAM240 and FAM300 models.",
    specs: [
      { label: "Diámetro", value: "3.700 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
      { label: "Caudal de aire", value: "5.000 m³/min" },
      { label: "Área de trabajo", value: "Hasta 200 m²" },
      { label: "Potencia", value: "0,37 kW" },
      { label: "Velocidad máxima", value: "100 RPM" },
      { label: "Alimentación", value: "220–240 / 380–460 V · 50/60 Hz" },
    ],
    specsEn: [
      { label: "Diameter", value: "3.700 mm" },
      { label: "Type", value: "Ceiling, high volume / low speed (HVLS)" },
      { label: "Air flow", value: "5,000 m³/min" },
      { label: "Working area", value: "Up to 200 m²" },
      { label: "Power", value: "0.37 kW" },
      { label: "Max. rotation speed", value: "100 RPM" },
      { label: "Power supply", value: "220–240 / 380–460 V · 50/60 Hz" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Almacenes y centros logísticos", "Pabellones deportivos"],
    aplicacionesEn: ["High-ceiling industrial buildings", "Warehouses and logistics centres", "Sports halls"],
    variantes: null,
  },
  {
    id: "fam430",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM430 · Ø4300 mm",
    resumen: "Ventilador de techo de la serie profesional BWP, gran diámetro.",
    resumenEn: "Ceiling fan from the professional BWP series, large diameter.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventiladores-de-techo-GRANDES-1-1024x1024.avif",
    imagenes: ["img/fam-430/fam430-caso-1.jpg", "img/fam-430/fam430-caso-2.jpg", "img/fam-430/fam430-caso-3.jpg", "img/fam-430/fam430-caso-4.jpg"],
    pvp: 1882,
    sageTools: "1021004",
    gid: null,
    destacado: false,
    descripcion: "Versión de la serie profesional BWP, con mayor diámetro y caudal que la serie FAM estándar. Pensado para naves de gran volumen.",
    descripcionEn: "A model from the professional BWP series, with greater diameter and airflow than the standard FAM series. Designed for large-volume buildings.",
    specs: [
      { label: "Diámetro", value: "4.300 mm" },
      { label: "Serie", value: "BWP (profesional)" },
      { label: "Caudal de aire", value: "7.000 m³/min" },
      { label: "Área de trabajo", value: "Hasta 450 m²" },
      { label: "Potencia", value: "0,75 kW" },
      { label: "Velocidad máxima", value: "90 RPM" },
      { label: "Alimentación", value: "220–240 / 380–460 V · 50/60 Hz" },
      { label: "Extra", value: "Incorpora inversor de giro" },
    ],
    specsEn: [
      { label: "Diameter", value: "4.300 mm" },
      { label: "Series", value: "BWP (professional)" },
      { label: "Air flow", value: "7,000 m³/min" },
      { label: "Working area", value: "Up to 450 m²" },
      { label: "Power", value: "0.75 kW" },
      { label: "Max. rotation speed", value: "90 RPM" },
      { label: "Power supply", value: "220–240 / 380–460 V · 50/60 Hz" },
      { label: "Extra", value: "Built-in rotation-reversal inverter" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Centros logísticos", "Pabellones deportivos"],
    aplicacionesEn: ["Large-volume industrial buildings", "Logistics centres", "Sports halls"],
    variantes: null,
  },
  {
    id: "fam500",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM500 · Ø5000 mm",
    resumen: "Ventilador de techo de la serie profesional BWP, gran diámetro.",
    resumenEn: "Ceiling fan from the professional BWP series, large diameter.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventiladores-de-techo-GRANDES-1-1024x1024.avif",
    imagenes: ["img/fam-500/fam500-caso-1.jpg", "img/fam-500/fam500-caso-2.jpg", "img/fam-500/fam500-caso-3.jpg", "img/fam-500/fam500-caso-4.jpg"],
    pvp: 1882,
    sageTools: "1021005",
    gid: null,
    destacado: false,
    descripcion: "Versión de la serie profesional BWP con 5.000 mm de diámetro, para cubrir grandes superficies con un único equipo.",
    descripcionEn: "A 5,000 mm-diameter model from the professional BWP series, to cover large areas with a single unit.",
    specs: [
      { label: "Diámetro", value: "5.000 mm" },
      { label: "Serie", value: "BWP (profesional)" },
      { label: "Caudal de aire", value: "10.000 m³/min" },
      { label: "Área de trabajo", value: "Hasta 500 m²" },
      { label: "Potencia", value: "0,75 kW" },
      { label: "Velocidad máxima", value: "80 RPM" },
      { label: "Alimentación", value: "220–240 / 380–460 V · 50/60 Hz" },
      { label: "Extra", value: "Incorpora inversor de giro" },
    ],
    specsEn: [
      { label: "Diameter", value: "5.000 mm" },
      { label: "Series", value: "BWP (professional)" },
      { label: "Air flow", value: "10,000 m³/min" },
      { label: "Working area", value: "Up to 500 m²" },
      { label: "Power", value: "0.75 kW" },
      { label: "Max. rotation speed", value: "80 RPM" },
      { label: "Power supply", value: "220–240 / 380–460 V · 50/60 Hz" },
      { label: "Extra", value: "Built-in rotation-reversal inverter" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Centros logísticos", "Pabellones deportivos"],
    aplicacionesEn: ["Large-volume industrial buildings", "Logistics centres", "Sports halls"],
    variantes: null,
  },
  {
    id: "fam610",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM610 · Ø6100 mm",
    resumen: "El mayor diámetro de la serie profesional BWP.",
    resumenEn: "The largest diameter in the professional BWP series.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventiladores-de-techo-GRANDES-1-1024x1024.avif",
    imagenes: ["img/fam-610/fam610-caso-1.jpg", "img/fam-610/fam610-caso-2.jpg", "img/fam-610/fam610-caso-3.jpg", "img/fam-610/fam610-caso-4.jpg"],
    pvp: 2679,
    sageTools: "1021006",
    gid: null,
    destacado: false,
    descripcion: "El modelo de mayor diámetro de la serie BWP, para las naves y espacios de mayor superficie de la gama de ventilación de techo Blizzcool.",
    descripcionEn: "The largest-diameter model in the BWP series, for the largest buildings and spaces in the Blizzcool ceiling fan range.",
    specs: [
      { label: "Diámetro", value: "6.100 mm" },
      { label: "Serie", value: "BWP (profesional)" },
      { label: "Caudal de aire", value: "11.500 m³/min" },
      { label: "Área de trabajo", value: "Hasta 1.000 m²" },
      { label: "Potencia", value: "1,5 kW" },
      { label: "Velocidad máxima", value: "65 RPM" },
      { label: "Alimentación", value: "220–240 / 380–460 V · 50/60 Hz" },
      { label: "Extra", value: "Incorpora inversor de giro" },
    ],
    specsEn: [
      { label: "Diameter", value: "6.100 mm" },
      { label: "Series", value: "BWP (professional)" },
      { label: "Air flow", value: "11,500 m³/min" },
      { label: "Working area", value: "Up to 1,000 m²" },
      { label: "Power", value: "1.5 kW" },
      { label: "Max. rotation speed", value: "65 RPM" },
      { label: "Power supply", value: "220–240 / 380–460 V · 50/60 Hz" },
      { label: "Extra", value: "Built-in rotation-reversal inverter" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Pabellones y grandes superficies"],
    aplicacionesEn: ["Large-volume industrial buildings", "Sports halls and large venues"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES PORTÁTILES ----------
  {
    id: "gd-120",
    categoria: "ventiladores-portatiles",
    nombre: "GD 120 · Ø1200 mm",
    resumen: "Ventilador móvil de suelo, motor BLDC de bajo consumo.",
    resumenEn: "Mobile floor fan with a low-consumption BLDC motor.",
    imagen: "img/gd-120/gd-120.jpg",
    imagenes: [
      { src: "img/gd-120/gd-120-angulo-1.jpg", fit: "contain" },
      { src: "img/gd-120/gd-120-angulo-2.jpg", fit: "contain" },
      { src: "img/gd-120/gd-120-diametro.jpg", fit: "contain" },
      { src: "img/gd-120/gd-120-silueta.jpg", fit: "contain" },
    ],
    pvp: 1350,
    sageTools: "1020001",
    gid: null,
    destacado: true,
    descripcion: "Ventilador portátil diseñado desde el origen para mover el aire en espacios de cientos o miles de m², no doméstico reconvertido. La tecnología BLDC (motor de corriente continua sin escobillas) ofrece caudales elevados con consumo mínimo.",
    descripcionEn: "Portable fan designed from the ground up to move air across hundreds or thousands of m², not a converted domestic unit. BLDC (brushless DC motor) technology delivers high airflow with minimal consumption.",
    specs: [
      { label: "Diámetro", value: "1.200 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales — reubicación sin herramientas" },
      { label: "Caudal de aire", value: "30.000 m³/h" },
      { label: "Área de trabajo", value: "Hasta 80 m²" },
      { label: "Potencia", value: "0,55 kW" },
      { label: "Velocidad máxima", value: "600 RPM" },
      { label: "Alimentación", value: "220 V / 50 Hz" },
    ],
    specsEn: [
      { label: "Diameter", value: "1.200 mm" },
      { label: "Motor", value: "Brushless DC (BLDC)" },
      { label: "Mobility", value: "Industrial castors — tool-free relocation" },
      { label: "Air flow", value: "30,000 m³/h" },
      { label: "Working area", value: "Up to 80 m²" },
      { label: "Power", value: "0.55 kW" },
      { label: "Max. speed", value: "600 RPM" },
      { label: "Power supply", value: "220 V / 50 Hz" },
    ],
    aplicaciones: ["Naves con puertas abiertas o ventilación natural", "Talleres", "Almacenes con tráfico constante de mercancía", "Pistas y banquillos deportivos"],
    aplicacionesEn: ["Buildings with open doors or natural ventilation", "Workshops", "Warehouses with constant goods traffic", "Sports courts and team benches"],
    variantes: null,
  },
  {
    id: "gd-150",
    categoria: "ventiladores-portatiles",
    nombre: "GD 150 · Ø1500 mm",
    resumen: "Ventilador móvil de mayor diámetro que el GD 120.",
    resumenEn: "Mobile fan with a larger diameter than the GD 120.",
    imagen: "img/gd-150/gd-150.jpg",
    imagenes: [
      { src: "img/gd-150/gd-150-angulo-1.jpg", fit: "contain" },
      { src: "img/gd-150/gd-150-angulo-2.jpg", fit: "contain" },
      { src: "img/gd-150/gd-150-diametro.jpg", fit: "contain" },
      { src: "img/gd-150/gd-150-silueta.jpg", fit: "contain" },
    ],
    pvp: 1650,
    sageTools: "1020002",
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor diámetro de la serie GD, con motor BLDC de bajo consumo y ruedas industriales para reubicación inmediata.",
    descripcionEn: "A larger-diameter model from the GD series, with a low-consumption BLDC motor and industrial castors for immediate relocation.",
    specs: [
      { label: "Diámetro", value: "1.500 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales" },
      { label: "Caudal de aire", value: "55.000 m³/h" },
      { label: "Área de trabajo", value: "Hasta 150 m²" },
      { label: "Potencia", value: "0,75 kW" },
      { label: "Velocidad máxima", value: "420 RPM" },
      { label: "Alimentación", value: "220 V / 50 Hz" },
    ],
    specsEn: [
      { label: "Diameter", value: "1.500 mm" },
      { label: "Motor", value: "Brushless DC (BLDC)" },
      { label: "Mobility", value: "Industrial castors" },
      { label: "Air flow", value: "55,000 m³/h" },
      { label: "Working area", value: "Up to 150 m²" },
      { label: "Power", value: "0.75 kW" },
      { label: "Max. speed", value: "420 RPM" },
      { label: "Power supply", value: "220 V / 50 Hz" },
    ],
    aplicaciones: ["Naves y almacenes de mayor superficie", "Talleres", "Pabellones y pistas deportivas"],
    aplicacionesEn: ["Larger industrial buildings and warehouses", "Workshops", "Sports halls and courts"],
    variantes: null,
  },
  {
    id: "gd-200",
    categoria: "ventiladores-portatiles",
    nombre: "GD 200 · Ø2000 mm",
    resumen: "El modelo de mayor diámetro de la serie GD portátil.",
    resumenEn: "The largest-diameter unit in the portable GD series.",
    imagen: "img/gd-200/gd-200.jpg",
    imagenes: [
      { src: "img/gd-200/gd-200-angulo-1.jpg", fit: "contain" },
      { src: "img/gd-200/gd-200-angulo-2.jpg", fit: "contain" },
      { src: "img/gd-200/gd-200-diametro.jpg", fit: "contain" },
      { src: "img/gd-200/gd-200-silueta.jpg", fit: "contain" },
    ],
    pvp: 1890,
    sageTools: "1020003",
    gid: null,
    destacado: false,
    descripcion: "El equipo de mayor caudal de la serie de ventiladores portátiles GD, para espacios de gran superficie que necesitan movilidad total.",
    descripcionEn: "The highest-airflow unit in the portable GD fan series, for large-floor-area spaces that need total mobility.",
    specs: [
      { label: "Diámetro", value: "2.000 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales" },
      { label: "Caudal de aire", value: "80.000 m³/h" },
      { label: "Área de trabajo", value: "Hasta 260 m²" },
      { label: "Potencia", value: "1 kW" },
      { label: "Velocidad máxima", value: "300 RPM" },
      { label: "Alimentación", value: "220 V / 50 Hz" },
    ],
    specsEn: [
      { label: "Diameter", value: "2.000 mm" },
      { label: "Motor", value: "Brushless DC (BLDC)" },
      { label: "Mobility", value: "Industrial castors" },
      { label: "Air flow", value: "80,000 m³/h" },
      { label: "Working area", value: "Up to 260 m²" },
      { label: "Power", value: "1 kW" },
      { label: "Max. speed", value: "300 RPM" },
      { label: "Power supply", value: "220 V / 50 Hz" },
    ],
    aplicaciones: ["Naves industriales de gran superficie", "Centros logísticos", "Pabellones deportivos de grandes dimensiones"],
    aplicacionesEn: ["Large-footprint industrial buildings", "Logistics centres", "Large sports halls"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES DE PARED ----------
  {
    id: "bp-600",
    categoria: "ventiladores-pared",
    nombre: "BP 600",
    resumen: "Ventilador industrial de pared, entrada de gama.",
    resumenEn: "Entry-level industrial wall fan.",
    imagen: "img/bp-600/bp-600.jpg",
    imagenes: [
      { src: "img/bp-600/bp-600-45view.jpg", fit: "contain" },
      { src: "img/bp-600/bp-600-angulos.jpg", fit: "contain" },
      { src: "img/bp-600/bp-600-blades.jpg", fit: "contain" },
      { src: "img/bp-600/bp-600-motor.jpg", fit: "contain" },
      { src: "img/bp-600/bp-600-diametro.jpg", fit: "contain" },
    ],
    pvp: 1080,
    sageTools: "1022001",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de pared para ventilación forzada en espacios que no retienen el frío de un climatizador: naves con puertas abiertas, talleres con ventilación natural o almacenes con tráfico constante.",
    descripcionEn: "Wall fan for forced ventilation in spaces that can't hold the cold air from a climate control unit: buildings with open doors, workshops with natural ventilation, or warehouses with constant traffic.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
      { label: "Diámetro", value: "600 mm" },
      { label: "Caudal de aire", value: "10.200 m³/h" },
      { label: "Velocidad del aire", value: "6,8 m/s" },
      { label: "Potencia", value: "0,55 kW" },
      { label: "Velocidad máxima", value: "1.050 RPM" },
      { label: "Alcance del aire", value: "15 m" },
      { label: "Nivel sonoro", value: "45 dB" },
      { label: "Alimentación", value: "220 / 380 V · 50/60 Hz" },
    ],
    specsEn: [
      { label: "Type", value: "Industrial wall fan" },
      { label: "Diameter", value: "600 mm" },
      { label: "Air flow", value: "10,200 m³/h" },
      { label: "Air speed", value: "6.8 m/s" },
      { label: "Power", value: "0.55 kW" },
      { label: "Max. speed", value: "1,050 RPM" },
      { label: "Air throw", value: "15 m" },
      { label: "Noise level", value: "45 dB" },
      { label: "Power supply", value: "220 / 380 V · 50/60 Hz" },
    ],
    aplicaciones: ["Talleres", "Almacenes", "Naves con ventilación natural", "Gimnasios y salas deportivas"],
    aplicacionesEn: ["Workshops", "Warehouses", "Buildings with natural ventilation", "Gyms and sports rooms"],
    variantes: null,
  },
  {
    id: "bp-900",
    categoria: "ventiladores-pared",
    nombre: "BP 900",
    resumen: "Ventilador industrial de pared de mayor caudal que el BP 600.",
    resumenEn: "Industrial wall fan with higher airflow than the BP 600.",
    imagen: "img/bp-900/bp-900.jpg",
    imagenes: [
      { src: "img/bp-900/bp-900-45view.jpg", fit: "contain" },
      { src: "img/bp-900/bp-900-angulos.jpg", fit: "contain" },
      { src: "img/bp-900/bp-900-blades.jpg", fit: "contain" },
      { src: "img/bp-900/bp-900-motor.jpg", fit: "contain" },
      { src: "img/bp-900/bp-900-diametro.jpg", fit: "contain" },
    ],
    pvp: 1187,
    sageTools: "1022002",
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor caudal de la serie BP, para espacios de pared donde se necesita mover más volumen de aire.",
    descripcionEn: "A higher-airflow model from the BP series, for wall-mounted applications where more air volume needs to be moved.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
      { label: "Diámetro", value: "900 mm" },
      { label: "Caudal de aire", value: "16.000 m³/h" },
      { label: "Velocidad del aire", value: "6,8 m/s" },
      { label: "Potencia", value: "0,55 kW" },
      { label: "Velocidad máxima", value: "870 RPM" },
      { label: "Alcance del aire", value: "20 m" },
      { label: "Nivel sonoro", value: "45 dB" },
      { label: "Alimentación", value: "220 / 380 V · 50/60 Hz" },
    ],
    specsEn: [
      { label: "Type", value: "Industrial wall fan" },
      { label: "Diameter", value: "900 mm" },
      { label: "Air flow", value: "16,000 m³/h" },
      { label: "Air speed", value: "6.8 m/s" },
      { label: "Power", value: "0.55 kW" },
      { label: "Max. speed", value: "870 RPM" },
      { label: "Air throw", value: "20 m" },
      { label: "Noise level", value: "45 dB" },
      { label: "Power supply", value: "220 / 380 V · 50/60 Hz" },
    ],
    aplicaciones: ["Talleres", "Almacenes", "Naves con ventilación natural", "Gimnasios y salas deportivas"],
    aplicacionesEn: ["Workshops", "Warehouses", "Buildings with natural ventilation", "Gyms and sports rooms"],
    variantes: null,
  },
  {
    id: "bp-1200",
    categoria: "ventiladores-pared",
    nombre: "BP 1200",
    resumen: "El modelo de mayor caudal de la serie de ventiladores de pared BP.",
    resumenEn: "The highest-airflow unit in the BP wall fan series.",
    imagen: "img/bp-1200/bp-1200.jpg",
    imagenes: [
      { src: "img/bp-1200/bp-1200-45view.jpg", fit: "contain" },
      { src: "img/bp-1200/bp-1200-angulos.jpg", fit: "contain" },
      { src: "img/bp-1200/bp-1200-blades.jpg", fit: "contain" },
      { src: "img/bp-1200/bp-1200-motor.jpg", fit: "contain" },
      { src: "img/bp-1200/bp-1200-diametro.jpg", fit: "contain" },
    ],
    pvp: 1329,
    sageTools: "1022003",
    gid: null,
    destacado: false,
    descripcion: "El equipo de mayores prestaciones de la serie BP, para naves y espacios de pared que requieren el máximo caudal de ventilación forzada.",
    descripcionEn: "The top-performing model in the BP wall fan series, for buildings and wall-mounted applications that need maximum forced-ventilation airflow.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
      { label: "Diámetro", value: "1.200 mm" },
      { label: "Caudal de aire", value: "26.000 m³/h" },
      { label: "Velocidad del aire", value: "6,3 m/s" },
      { label: "Potencia", value: "0,75 kW" },
      { label: "Velocidad máxima", value: "600 RPM" },
      { label: "Alcance del aire", value: "20 m" },
      { label: "Nivel sonoro", value: "45 dB" },
      { label: "Alimentación", value: "220 / 380 V · 50/60 Hz" },
    ],
    specsEn: [
      { label: "Type", value: "Industrial wall fan" },
      { label: "Diameter", value: "1,200 mm" },
      { label: "Air flow", value: "26,000 m³/h" },
      { label: "Air speed", value: "6.3 m/s" },
      { label: "Power", value: "0.75 kW" },
      { label: "Max. speed", value: "600 RPM" },
      { label: "Air throw", value: "20 m" },
      { label: "Noise level", value: "45 dB" },
      { label: "Power supply", value: "220 / 380 V · 50/60 Hz" },
    ],
    aplicaciones: ["Naves industriales", "Almacenes de gran superficie", "Pabellones deportivos"],
    aplicacionesEn: ["Industrial buildings", "Large-footprint warehouses", "Sports halls"],
    variantes: null,
  },
  // ---------- RECAMBIOS Y POST-VENTA ----------
  {
    id: "bomba-bc",
    categoria: "recambios",
    nombre: "Bomba enfriador BC200 / BC290 / BC395",
    resumen: "Recambio de bomba de agua para toda la gama de enfriadores evaporativos BC.",
    resumenEn: "Replacement water pump for the full BC evaporative cooler range.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Bomba-de-Agua-1024x1024.avif",
    pvp: 59.9,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el circuito de agua. Elige el modelo de tu enfriador evaporativo para ver el precio y la referencia exactos.",
    descripcionEn: "Original Blizzcool spare part for the water circuit. Choose your evaporative cooler model to see the exact price and reference code.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290, BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200, BC290, BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: [
      { modelo: "BC200 / BC290", pvp: 59.9, sageTools: "1019001" },
      { modelo: "BC395", pvp: 72.25, sageTools: "1019002" },
    ],
  },
  {
    id: "filtros-bc",
    categoria: "recambios",
    nombre: "Paquete de filtros BC200 / BC290 / BC395 (3 uds.)",
    resumen: "Recambio de filtros (pack de 3) para toda la gama de enfriadores evaporativos BC.",
    resumenEn: "Replacement filter pack (3 units) for the full BC evaporative cooler range.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Filtro2-1-1024x1024.avif",
    pvp: 93.25,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Paquete de 3 filtros de recambio originales Blizzcool. Elige el modelo de tu enfriador evaporativo para ver el precio y la referencia exactos.",
    descripcionEn: "Pack of 3 original Blizzcool replacement filters. Choose your evaporative cooler model to see the exact price and reference code.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290, BC395" },
      { label: "Unidades", value: "3" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200, BC290, BC395" },
      { label: "Units", value: "3" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: [
      { modelo: "BC200", pvp: 93.25, sageTools: "1018001" },
      { modelo: "BC290", pvp: 104, sageTools: "1018002" },
      { modelo: "BC395", pvp: 147.35, sageTools: "1018003" },
    ],
  },
  {
    id: "generador-anion",
    categoria: "recambios",
    nombre: "Generador de anión",
    resumen: "Recambio del generador de aniones para enfriadores evaporativos Blizzcool.",
    resumenEn: "Replacement anion generator for Blizzcool evaporative coolers.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Generador-de-Anion-1024x1024.avif",
    pvp: 59.9,
    sageTools: "1019010",
    gid: "5176.16",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el sistema de generación de aniones incorporado en los enfriadores evaporativos.",
    descripcionEn: "Original Blizzcool spare part for the anion-generation system built into the evaporative coolers.",
    specs: [
      { label: "Tipo", value: "Recambio — generador de aniones" },
    ],
    specsEn: [
      { label: "Type", value: "Spare part — anion generator" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "panel-control-bc",
    categoria: "recambios",
    nombre: "Panel de control BC200 / BC290 / BC395",
    resumen: "Recambio de panel de control para toda la gama de enfriadores BC.",
    resumenEn: "Replacement control panel for the full BC cooler range.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Panel-de-Control-Frente-1024x1024.avif",
    pvp: 59.95,
    sageTools: "1019003",
    gid: "5176.23",
    destacado: false,
    descripcion: "Panel de control de recambio original Blizzcool, compatible con los tres modelos de la gama de enfriadores evaporativos BC.",
    descripcionEn: "Original Blizzcool replacement control panel, compatible with all three models in the BC evaporative cooler range.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290, BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200, BC290, BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "helice-bc",
    categoria: "recambios",
    nombre: "Hélice enfriador BC200 / BC290 / BC395",
    resumen: "Recambio de hélice para toda la gama de enfriadores evaporativos BC.",
    resumenEn: "Replacement fan blade for the full BC evaporative cooler range.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Helice-BC200-1-1024x1024.avif",
    pvp: 28.5,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool. Elige el modelo de tu enfriador evaporativo para ver el precio y la referencia exactos.",
    descripcionEn: "Original Blizzcool spare part. Choose your evaporative cooler model to see the exact price and reference code.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290, BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200, BC290, BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: [
      { modelo: "BC200", pvp: 28.5, sageTools: "1019004" },
      { modelo: "BC290", pvp: 56.35, sageTools: "1019005" },
      { modelo: "BC395", pvp: 78.48, sageTools: "1019006" },
    ],
  },
  {
    id: "parrilla-bc",
    categoria: "recambios",
    nombre: "Parrilla enfriador BC200 / BC290 / BC395",
    resumen: "Recambio de parrilla para toda la gama de enfriadores evaporativos BC.",
    resumenEn: "Replacement grille for the full BC evaporative cooler range.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Rejilla-1024x1024.avif",
    pvp: 22.8,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool. Elige el modelo de tu enfriador evaporativo para ver el precio y la referencia exactos.",
    descripcionEn: "Original Blizzcool spare part. Choose your evaporative cooler model to see the exact price and reference code.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290, BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200, BC290, BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: [
      { modelo: "BC200", pvp: 22.8, sageTools: "1019007" },
      { modelo: "BC290", pvp: 40.25, sageTools: "1019008" },
      { modelo: "BC395", pvp: 50.49, sageTools: "1019009" },
    ],
  },
];
