/**
 * CATÁLOGO BLIZZCOOL — fichero de datos
 * ---------------------------------------------------
 * Precios: columna PVP de la tarifa oficial (TARIFA_BLIZZCOOL_NETOS_Y_REVENDEDORES.xlsx),
 * siempre SIN IVA. El sitio calcula el 21% de IVA con el interruptor de la cabecera.
 *
 * Cómo alimentar este fichero:
 * - imagen: ruta a la foto del equipo (ej. "img/ac-1900-1.jpg"). Déjalo en null si aún no hay foto.
 * - pvp: precio de venta al público SIN IVA (número). Es el precio de referencia de la tarifa.
 * - specs: lista de { label, value } — lo que sale en la ficha técnica.
 * - sageTools / gid: códigos internos de la tarifa, se muestran como referencia en la ficha.
 * - No borres ningún campo aunque esté vacío: usa null o "" para no romper la página.
 * - Para añadir un producto nuevo, copia un bloque entero y cambia el "id" (debe ser único, sin espacios).
 */

const CATEGORIAS = [
  { id: "aire-acondicionado", nombre: "Aire acondicionado industrial portátil", nombreEn: "Portable industrial air conditioning" },
  { id: "enfriadores-evaporativos", nombre: "Enfriadores evaporativos industriales", nombreEn: "Industrial evaporative coolers" },
  { id: "nebulizadores", nombre: "Nebulizadores industriales", nombreEn: "Industrial misting fans" },
  { id: "ventiladores-techo", nombre: "Ventiladores industriales de techo", nombreEn: "Industrial ceiling fans" },
  { id: "ventiladores-portatiles", nombre: "Ventiladores industriales portátiles", nombreEn: "Portable industrial fans" },
  { id: "ventiladores-pared", nombre: "Ventiladores industriales de pared", nombreEn: "Industrial wall fans" },
  { id: "ropa-termica", nombre: "Ropa térmica y refrigerante", nombreEn: "Thermal & cooling workwear" },
  { id: "recambios", nombre: "Recambios y post-venta", nombreEn: "Spare parts & after-sales" },
];

const PRODUCTOS = [
  // ---------- AIRE ACONDICIONADO INDUSTRIAL PORTÁTIL ----------
  {
    id: "ac-1900-1",
    categoria: "aire-acondicionado",
    nombre: "AC-1900/1",
    resumen: "Spot cooler compacto para espacios medianos, oficinas y locales sin obra.",
    resumenEn: "Compact spot cooler for medium-sized spaces, offices and premises with no building work.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/aire-acondicionado-portatil-ac-1900-1.avif",
    pvp: 695,
    sageTools: "1030001",
    gid: "5252.5",
    destacado: true,
    descripcion: "Aire acondicionado portátil por compresor, listo para enfriar con un simple enchufe estándar y un tubo de evacuación al exterior. Pensado para locales comerciales, oficinas en alquiler o como equipo de emergencia cuando falla un sistema fijo.",
    descripcionEn: "Portable compressor air conditioner, ready to cool with a standard plug and an exhaust duct to the outside. Designed for commercial premises, rented offices, or as a backup unit when a fixed system fails.",
    specs: [
      { label: "Alimentación", value: "220–240 V / 50 Hz" },
      { label: "Capacidad frigorífica", value: "2,0 kW (2.000 frigorías)" },
      { label: "Potencia nominal", value: "700 W" },
      { label: "Corriente nominal", value: "3,2 A" },
      { label: "Caudal de aire", value: "230 m³/h" },
      { label: "Refrigerante", value: "R290 (180 g)" },
      { label: "Ambiente de servicio", value: "20–43 °C" },
      { label: "Nivel sonoro", value: "52 dB(A)" },
      { label: "Dimensiones", value: "465 × 287 × 586 mm" },
      { label: "Peso neto / bruto", value: "25,5 kg / 28,3 kg" },
      { label: "Superficie recomendada", value: "Hasta 190 m²" },
    ],
    specsEn: [
      { label: "Power supply", value: "220–240 V / 50 Hz" },
      { label: "Cooling capacity", value: "2,0 kW (2.000 frigorías)" },
      { label: "Rated power", value: "700 W" },
      { label: "Rated current", value: "3,2 A" },
      { label: "Air flow", value: "230 m³/h" },
      { label: "Refrigerant", value: "R290 (180 g)" },
      { label: "Operating range", value: "20–43 °C" },
      { label: "Noise level", value: "52 dB(A)" },
      { label: "Dimensions", value: "465 × 287 × 586 mm" },
      { label: "Net / gross weight", value: "25,5 kg / 28,3 kg" },
      { label: "Recommended area", value: "Hasta 190 m²" },
    ],
    aplicaciones: ["Locales comerciales y oficinas en alquiler", "Salas de servidores pequeñas", "Equipo de emergencia ante avería de climatización fija", "Eventos y ferias"],
    aplicacionesEn: ["Rented commercial units and offices", "Small server rooms", "Emergency backup for fixed HVAC failure", "Events and trade fairs"],
    variantes: null,
  },
  {
    id: "ac-2700-1",
    categoria: "aire-acondicionado",
    nombre: "AC-2700/1",
    resumen: "Spot cooler intermedio para talleres y locales de tamaño medio.",
    resumenEn: "Mid-range spot cooler for workshops and medium-sized premises.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/aire-acondicionado-portatil-ac-2700-1.avif",
    pvp: 890,
    sageTools: "1030002",
    gid: "5252.1",
    destacado: false,
    descripcion: "Segundo escalón de la gama de spot coolers Blizzcool, entre el AC-1900/1 y el AC-3500/2. Refrigeración por compresor, portátil y sin necesidad de instalación fija. Es también la elección habitual para salas de servidores por su bajo consumo.",
    descripcionEn: "The second step in the Blizzcool spot cooler range, between the AC-1900/1 and the AC-3500/2. Compressor cooling, portable and with no need for fixed installation. Also the usual choice for server rooms thanks to its low consumption.",
    specs: [
      { label: "Capacidad frigorífica", value: "2.700 frigorías" },
      { label: "Caudal de aire", value: "400 m³/h" },
      { label: "Potencia nominal", value: "950 W" },
      { label: "Ambiente de servicio", value: "18–45 °C" },
      { label: "Refrigerante", value: "R290" },
      { label: "Peso neto", value: "42 kg" },
    ],
    specsEn: [
      { label: "Cooling capacity", value: "2.700 frigorías" },
      { label: "Air flow", value: "400 m³/h" },
      { label: "Rated power", value: "950 W" },
      { label: "Operating range", value: "18–45 °C" },
      { label: "Refrigerant", value: "R290" },
      { label: "Net weight", value: "42 kg" },
    ],
    aplicaciones: ["Talleres y locales comerciales medianos", "Salas de servidores y racks electrónicos", "Eventos y ferias"],
    aplicacionesEn: ["Workshops and medium-sized commercial units", "Server rooms and electronic racks", "Events and trade fairs"],
    variantes: null,
  },
  {
    id: "ac-3500-2",
    categoria: "aire-acondicionado",
    nombre: "AC-3500/2",
    resumen: "3.500 frigorías para talleres, almacenes y fábricas de tamaño medio.",
    resumenEn: "3,500 frigories for workshops, warehouses and mid-sized factories.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/aire-acondicionado-portatil-ac-3500-1.avif",
    pvp: 1165,
    sageTools: "1030003",
    gid: "5252.2",
    destacado: true,
    descripcion: "Sistema de refrigeración por compresor de alto rendimiento y bajo consumo, diseñado para trabajar de forma continua en entornos exigentes. Portátil, con ruedas y sin necesidad de instalación fija.",
    descripcionEn: "High-performance, low-consumption compressor cooling system, designed to run continuously in demanding environments. Portable, on wheels, with no need for fixed installation.",
    specs: [
      { label: "Capacidad frigorífica", value: "3.500 frigorías" },
      { label: "Caudal de aire", value: "600 m³/h" },
      { label: "Potencia nominal", value: "1.400 W" },
      { label: "Ambiente de servicio", value: "18–45 °C" },
      { label: "Refrigerante", value: "R290" },
      { label: "Peso neto", value: "49 kg" },
    ],
    specsEn: [
      { label: "Cooling capacity", value: "3.500 frigorías" },
      { label: "Air flow", value: "600 m³/h" },
      { label: "Rated power", value: "1.400 W" },
      { label: "Operating range", value: "18–45 °C" },
      { label: "Refrigerant", value: "R290" },
      { label: "Net weight", value: "49 kg" },
    ],
    aplicaciones: ["Talleres y almacenes", "Fábricas", "Eventos, ferias y exposiciones"],
    aplicacionesEn: ["Workshops and warehouses", "Factories", "Events, trade fairs and exhibitions"],
    variantes: null,
  },
  {
    id: "ac-5300-3",
    categoria: "aire-acondicionado",
    nombre: "AC-5300/3",
    resumen: "La referencia de mayor capacidad de la gama, para grandes superficies.",
    resumenEn: "The highest-capacity unit in the range, for large floor areas.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/aire-acondicionado-portatil-ac-5300-3.avif",
    pvp: 1990,
    sageTools: "1030004",
    gid: "5252.3",
    destacado: false,
    descripcion: "El modelo de mayores prestaciones de la gama de spot coolers Blizzcool. Refrigeración por compresor de alto rendimiento para naves y locales de gran superficie, operativo el mismo día sin obra ni permisos.",
    descripcionEn: "The top-performing model in the Blizzcool spot cooler range. High-performance compressor cooling for large industrial buildings and premises, operational the same day with no building work or permits.",
    specs: [
      { label: "Capacidad frigorífica", value: "5.300 frigorías" },
      { label: "Caudal de aire", value: "800 m³/h" },
      { label: "Potencia nominal", value: "2.200 W" },
      { label: "Ambiente de servicio", value: "18–45 °C" },
      { label: "Refrigerante", value: "R1234yf" },
      { label: "Peso neto", value: "95 kg" },
    ],
    specsEn: [
      { label: "Cooling capacity", value: "5.300 frigorías" },
      { label: "Air flow", value: "800 m³/h" },
      { label: "Rated power", value: "2.200 W" },
      { label: "Operating range", value: "18–45 °C" },
      { label: "Refrigerant", value: "R1234yf" },
      { label: "Net weight", value: "95 kg" },
    ],
    aplicaciones: ["Naves industriales de gran superficie", "Salas de servidores y centros de datos", "Locales comerciales grandes"],
    aplicacionesEn: ["Large-footprint industrial buildings", "Server rooms and data centres", "Large commercial premises"],
    variantes: null,
  },
  // ---------- ENFRIADORES EVAPORATIVOS INDUSTRIALES ----------
  {
    id: "bc-200",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 200",
    resumen: "Enfriador evaporativo de entrada de gama, para espacios medianos.",
    resumenEn: "Entry-level evaporative cooler for medium-sized spaces.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Enfriador-evaporativo-Blizzcool-BC-200-Frontal-2-1024x1024.avif",
    pvp: 1540,
    sageTools: "1010001",
    gid: "5176.7",
    destacado: false,
    descripcion: "Equipo de climatización por evaporación de agua: aspira aire caliente, lo hace pasar por paneles húmedos y lo devuelve más frío, sin gases refrigerantes ni compresor. Consumo eléctrico muy inferior al de un aire acondicionado equivalente.",
    descripcionEn: "Water-evaporation climate control unit: draws in hot air, passes it through wet pads and returns it cooler, with no refrigerant gases or compressor. Electricity consumption far lower than an equivalent air conditioner.",
    specs: [
      { label: "Tipo", value: "Enfriador evaporativo" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    specsEn: [
      { label: "Type", value: "Evaporative cooler" },
      { label: "Refrigerant", value: "No gases — water and air only" },
      { label: "Recommended climate", value: "Dry — relative humidity below 60%" },
    ],
    aplicaciones: ["Talleres y almacenes medianos", "Locales comerciales", "Espacios deportivos"],
    aplicacionesEn: ["Medium-sized workshops and warehouses", "Commercial premises", "Sports facilities"],
    variantes: null,
  },
  {
    id: "bc-290",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 290",
    resumen: "Enfriador evaporativo de gama media, mayor caudal que el BC 200.",
    resumenEn: "Mid-range evaporative cooler, higher airflow than the BC 200.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Enfriador-evaporativo-Blizzcool-BC-290-Frontal-2-1024x1024.avif",
    pvp: 1815,
    sageTools: "1010002",
    gid: "5176.2",
    destacado: false,
    descripcion: "Equipo de climatización por evaporación de agua, un escalón por encima del BC 200 en caudal de aire. Sin gases refrigerantes ni compresor, con un coste operativo muy inferior al del aire acondicionado tradicional.",
    descripcionEn: "Water-evaporation climate control unit, one step above the BC 200 in airflow. No refrigerant gases or compressor, with running costs far lower than traditional air conditioning.",
    specs: [
      { label: "Tipo", value: "Enfriador evaporativo" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    specsEn: [
      { label: "Type", value: "Evaporative cooler" },
      { label: "Refrigerant", value: "No gases — water and air only" },
      { label: "Recommended climate", value: "Dry — relative humidity below 60%" },
    ],
    aplicaciones: ["Naves y talleres", "Almacenes y centros logísticos", "Terrazas de hostelería"],
    aplicacionesEn: ["Industrial buildings and workshops", "Warehouses and logistics centres", "Hospitality terraces"],
    variantes: null,
  },
  {
    id: "bc-395",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 395",
    resumen: "Enfriador evaporativo de gran caudal para naves y espacios amplios.",
    resumenEn: "High-airflow evaporative cooler for industrial buildings and large spaces.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Enfriador-evaporativo-Blizzcool-BC-395-Frontal-2-1024x1024.avif",
    pvp: 2189,
    sageTools: "1010003",
    gid: "5176.3",
    destacado: true,
    descripcion: "Equipo de climatización por evaporación de agua: aspira aire caliente, lo hace pasar por paneles húmedos y lo devuelve hasta 15 °C más frío, sin gases refrigerantes ni compresor. Consumo eléctrico muy inferior al de un aire acondicionado equivalente.",
    descripcionEn: "Water-evaporation climate control unit: draws in hot air, passes it through wet pads and returns it up to 15 °C cooler, with no refrigerant gases or compressor. Electricity consumption far lower than an equivalent air conditioner.",
    specs: [
      { label: "Caudal de aire", value: "Hasta 345 m³/min" },
      { label: "Reducción de temperatura", value: "Entre 12 y 15 °C en condiciones óptimas" },
      { label: "Consumo estimado", value: "0,5–3 kW/h según modelo" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Extra", value: "Sistema anti-bacterias integrado" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    specsEn: [
      { label: "Air flow", value: "Hasta 345 m³/min" },
      { label: "Temperature drop", value: "Entre 12 y 15 °C en condiciones óptimas" },
      { label: "Estimated consumption", value: "0,5–3 kW/h según modelo" },
      { label: "Refrigerant", value: "No gases — water and air only" },
      { label: "Extra", value: "Integrated anti-bacterial system" },
      { label: "Recommended climate", value: "Dry — relative humidity below 60%" },
    ],
    aplicaciones: ["Naves industriales y de producción", "Talleres mecánicos y de carrocería", "Almacenes y centros logísticos", "Gimnasios y espacios deportivos", "Terrazas de hostelería"],
    aplicacionesEn: ["Industrial and production buildings", "Mechanical and bodywork workshops", "Warehouses and logistics centres", "Gyms and sports facilities", "Hospitality terraces"],
    variantes: null,
  },
  // ---------- NEBULIZADORES INDUSTRIALES ----------
  {
    id: "bsm-160l",
    categoria: "nebulizadores",
    nombre: "BSM160L",
    resumen: "Nebulizador de alto caudal con depósito de 160 litros para jornadas completas.",
    resumenEn: "High-flow misting fan with a 160-litre tank for full working days.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/Front-BSM160.avif",
    pvp: 2490.35,
    sageTools: "1040001",
    gid: "5176.24",
    destacado: true,
    descripcion: "Sistema de nebulización de gota fina (por debajo de 10 micras) que garantiza evaporación completa sin mojar personas ni superficies. Funciona con un simple enchufe estándar, sin instalación eléctrica específica.",
    descripcionEn: "Fine-droplet misting system (under 10 microns) that guarantees full evaporation without wetting people or surfaces. Runs off a standard plug socket, with no dedicated electrical installation.",
    specs: [
      { label: "Capacidad de depósito", value: "160 L" },
      { label: "Tamaño de gota", value: "Menos de 10 micras" },
      { label: "Alimentación", value: "Enchufe estándar" },
      { label: "Rendimiento óptimo", value: "Humedad relativa por debajo del 70–75%" },
    ],
    specsEn: [
      { label: "Tank capacity", value: "160 L" },
      { label: "Droplet size", value: "Menos de 10 micras" },
      { label: "Power supply", value: "Standard plug socket" },
      { label: "Optimal performance", value: "Humedad relativa por debajo del 70–75%" },
    ],
    aplicaciones: ["Naves industriales y logística", "Hostelería y terrazas", "Eventos deportivos y culturales"],
    aplicacionesEn: ["Industrial and logistics buildings", "Hospitality venues and terraces", "Sports and cultural events"],
    variantes: null,
  },
  {
    id: "bsm-380l",
    categoria: "nebulizadores",
    nombre: "BSM380L",
    resumen: "Máxima autonomía de la gama: depósito de 380 litros para eventos y grandes espacios.",
    resumenEn: "Maximum runtime in the range: 380-litre tank for events and large spaces.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/Front-BSM380.avif",
    pvp: 2992.28,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor depósito de la gama de nebulizadores industriales Blizzcool, pensada para jornadas o eventos completos sin recargas, cubriendo superficies de hasta 250 m² por equipo.",
    descripcionEn: "The largest-tank model in the Blizzcool misting fan range, designed for full working days or events with no refills, covering up to 250 m² per unit.",
    specs: [
      { label: "Capacidad de depósito", value: "380 L" },
      { label: "Cobertura", value: "Hasta 250 m² por equipo" },
      { label: "Tamaño de gota", value: "Menos de 10 micras" },
      { label: "Alimentación", value: "Enchufe estándar" },
    ],
    specsEn: [
      { label: "Tank capacity", value: "380 L" },
      { label: "Coverage", value: "Hasta 250 m² por equipo" },
      { label: "Droplet size", value: "Menos de 10 micras" },
      { label: "Power supply", value: "Standard plug socket" },
    ],
    aplicaciones: ["Pabellones y campus deportivos sin climatización centralizada", "Eventos y ferias exteriores", "Zonas VIP y áreas de calentamiento"],
    aplicacionesEn: ["Sports halls and campuses without central HVAC", "Outdoor events and trade fairs", "VIP areas and warm-up zones"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES DE TECHO ----------
  {
    id: "fam240",
    categoria: "ventiladores-techo",
    nombre: "BW FAM240 · Ø2400 mm",
    resumen: "Ventilador de techo de gran diámetro, entrada de gama de la serie FAM.",
    resumenEn: "Large-diameter ceiling fan, entry point of the FAM series.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-de-Techo-BUENA-WEB-1024x1024.avif",
    pvp: 1090,
    sageTools: "1021001",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad. Mueve grandes volúmenes de aire con un consumo mucho menor que un equipo de climatización de potencia equivalente, sin necesidad de enfriar todo el volumen de la nave.",
    descripcionEn: "High-volume, low-speed ceiling fan. Moves large volumes of air with far lower consumption than an equivalent-power HVAC unit, without needing to cool the whole volume of the building.",
    specs: [
      { label: "Diámetro", value: "2.400 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
    ],
    specsEn: [
      { label: "Diameter", value: "2.400 mm" },
      { label: "Type", value: "Ceiling, high volume / low speed (HVLS)" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Complemento de climatización existente"],
    aplicacionesEn: ["High-ceiling industrial buildings", "Complement to existing HVAC"],
    variantes: null,
  },
  {
    id: "fam300",
    categoria: "ventiladores-techo",
    nombre: "BW FAM300 · Ø3000 mm",
    resumen: "Ventilador de techo de la serie FAM, un escalón por encima del FAM240.",
    resumenEn: "Ceiling fan from the FAM series, one step up from the FAM240.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-de-Techo-BUENA-WEB-1024x1024.avif",
    pvp: 1120,
    sageTools: "1021002",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad, con mayor diámetro que el FAM240 para cubrir superficies más amplias.",
    descripcionEn: "High-volume, low-speed ceiling fan, with a larger diameter than the FAM240 to cover wider areas.",
    specs: [
      { label: "Diámetro", value: "3.000 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
    ],
    specsEn: [
      { label: "Diameter", value: "3.000 mm" },
      { label: "Type", value: "Ceiling, high volume / low speed (HVLS)" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Complemento de climatización existente"],
    aplicacionesEn: ["High-ceiling industrial buildings", "Complement to existing HVAC"],
    variantes: null,
  },
  {
    id: "fam370",
    categoria: "ventiladores-techo",
    nombre: "BW FAM370 · Ø3700 mm",
    resumen: "Ventilador de techo de gran diámetro para naves amplias.",
    resumenEn: "Large-diameter ceiling fan for spacious industrial buildings.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-de-Techo-BUENA-WEB-1024x1024.avif",
    pvp: 1190,
    sageTools: "1021003",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad, pensado para espacios de mayor superficie que los modelos FAM240 y FAM300.",
    descripcionEn: "High-volume, low-speed ceiling fan, designed for larger-floor-area buildings than the FAM240 and FAM300 models.",
    specs: [
      { label: "Diámetro", value: "3.700 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
    ],
    specsEn: [
      { label: "Diameter", value: "3.700 mm" },
      { label: "Type", value: "Ceiling, high volume / low speed (HVLS)" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Almacenes y centros logísticos"],
    aplicacionesEn: ["High-ceiling industrial buildings", "Warehouses and logistics centres"],
    variantes: null,
  },
  {
    id: "fam430",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM430 · Ø4300 mm",
    resumen: "Ventilador de techo de la serie profesional BWP, gran diámetro.",
    resumenEn: "Ceiling fan from the professional BWP series, large diameter.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventiladores-de-techo-GRANDES-1-1024x1024.avif",
    pvp: 1882,
    sageTools: "1021004",
    gid: null,
    destacado: false,
    descripcion: "Versión de la serie profesional BWP, con mayor diámetro y caudal que la serie FAM estándar. Pensado para naves de gran volumen.",
    descripcionEn: "A model from the professional BWP series, with greater diameter and airflow than the standard FAM series. Designed for large-volume buildings.",
    specs: [
      { label: "Diámetro", value: "4.300 mm" },
      { label: "Serie", value: "BWP (profesional)" },
    ],
    specsEn: [
      { label: "Diameter", value: "4.300 mm" },
      { label: "Series", value: "BWP (professional)" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Centros logísticos"],
    aplicacionesEn: ["Large-volume industrial buildings", "Logistics centres"],
    variantes: null,
  },
  {
    id: "fam500",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM500 · Ø5000 mm",
    resumen: "Ventilador de techo de la serie profesional BWP, gran diámetro.",
    resumenEn: "Ceiling fan from the professional BWP series, large diameter.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventiladores-de-techo-GRANDES-1-1024x1024.avif",
    pvp: 1882,
    sageTools: "1021005",
    gid: null,
    destacado: false,
    descripcion: "Versión de la serie profesional BWP con 5.000 mm de diámetro, para cubrir grandes superficies con un único equipo.",
    descripcionEn: "A 5,000 mm-diameter model from the professional BWP series, to cover large areas with a single unit.",
    specs: [
      { label: "Diámetro", value: "5.000 mm" },
      { label: "Serie", value: "BWP (profesional)" },
    ],
    specsEn: [
      { label: "Diameter", value: "5.000 mm" },
      { label: "Series", value: "BWP (professional)" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Centros logísticos"],
    aplicacionesEn: ["Large-volume industrial buildings", "Logistics centres"],
    variantes: null,
  },
  {
    id: "fam610",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM610 · Ø6100 mm",
    resumen: "El mayor diámetro de la serie profesional BWP.",
    resumenEn: "The largest diameter in the professional BWP series.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventiladores-de-techo-GRANDES-1-1024x1024.avif",
    pvp: 2679,
    sageTools: "1021006",
    gid: null,
    destacado: false,
    descripcion: "El modelo de mayor diámetro de la serie BWP, para las naves y espacios de mayor superficie de la gama de ventilación de techo Blizzcool.",
    descripcionEn: "The largest-diameter model in the BWP series, for the largest buildings and spaces in the Blizzcool ceiling fan range.",
    specs: [
      { label: "Diámetro", value: "6.100 mm" },
      { label: "Serie", value: "BWP (profesional)" },
    ],
    specsEn: [
      { label: "Diameter", value: "6.100 mm" },
      { label: "Series", value: "BWP (professional)" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Pabellones y grandes superficies"],
    aplicacionesEn: ["Large-volume industrial buildings", "Sports halls and large venues"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES PORTÁTILES ----------
  {
    id: "gd-120",
    categoria: "ventiladores-portatiles",
    nombre: "GD 120 · Ø1200 mm",
    resumen: "Ventilador móvil de suelo, motor BLDC de bajo consumo.",
    resumenEn: "Mobile floor fan with a low-consumption BLDC motor.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-Movil-Blizzcool-HDY-12-32-O1200-Buena-1-1024x1024.avif",
    pvp: 1350,
    sageTools: "1020001",
    gid: null,
    destacado: true,
    descripcion: "Ventilador portátil diseñado desde el origen para mover el aire en espacios de cientos o miles de m², no doméstico reconvertido. La tecnología BLDC (motor de corriente continua sin escobillas) ofrece caudales elevados con consumo mínimo.",
    descripcionEn: "Portable fan designed from the ground up to move air across hundreds or thousands of m², not a converted domestic unit. BLDC (brushless DC motor) technology delivers high airflow with minimal consumption.",
    specs: [
      { label: "Diámetro", value: "1.200 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales — reubicación sin herramientas" },
    ],
    specsEn: [
      { label: "Diameter", value: "1.200 mm" },
      { label: "Motor", value: "Brushless DC (BLDC)" },
      { label: "Mobility", value: "Industrial castors — tool-free relocation" },
    ],
    aplicaciones: ["Naves con puertas abiertas o ventilación natural", "Talleres", "Almacenes con tráfico constante de mercancía"],
    aplicacionesEn: ["Buildings with open doors or natural ventilation", "Workshops", "Warehouses with constant goods traffic"],
    variantes: null,
  },
  {
    id: "gd-150",
    categoria: "ventiladores-portatiles",
    nombre: "GD 150 · Ø1500 mm",
    resumen: "Ventilador móvil de mayor diámetro que el GD 120.",
    resumenEn: "Mobile fan with a larger diameter than the GD 120.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-Movil-Blizzcool-HDY-15-32-O1500-Buen-2-1024x1024.avif",
    pvp: 1650,
    sageTools: "1020002",
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor diámetro de la serie GD, con motor BLDC de bajo consumo y ruedas industriales para reubicación inmediata.",
    descripcionEn: "A larger-diameter model from the GD series, with a low-consumption BLDC motor and industrial castors for immediate relocation.",
    specs: [
      { label: "Diámetro", value: "1.500 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales" },
    ],
    specsEn: [
      { label: "Diameter", value: "1.500 mm" },
      { label: "Motor", value: "Brushless DC (BLDC)" },
      { label: "Mobility", value: "Industrial castors" },
    ],
    aplicaciones: ["Naves y almacenes de mayor superficie", "Talleres"],
    aplicacionesEn: ["Larger industrial buildings and warehouses", "Workshops"],
    variantes: null,
  },
  {
    id: "gd-200",
    categoria: "ventiladores-portatiles",
    nombre: "GD 200 · Ø2000 mm",
    resumen: "El modelo de mayor diámetro de la serie GD portátil.",
    resumenEn: "The largest-diameter unit in the portable GD series.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Ventilador-Movil-Blizzcool-HDY-2-32-O2000-Buena-2-1024x1024.avif",
    pvp: 1890,
    sageTools: "1020003",
    gid: null,
    destacado: false,
    descripcion: "El equipo de mayor caudal de la serie de ventiladores portátiles GD, para espacios de gran superficie que necesitan movilidad total.",
    descripcionEn: "The highest-airflow unit in the portable GD fan series, for large-floor-area spaces that need total mobility.",
    specs: [
      { label: "Diámetro", value: "2.000 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales" },
    ],
    specsEn: [
      { label: "Diameter", value: "2.000 mm" },
      { label: "Motor", value: "Brushless DC (BLDC)" },
      { label: "Mobility", value: "Industrial castors" },
    ],
    aplicaciones: ["Naves industriales de gran superficie", "Centros logísticos"],
    aplicacionesEn: ["Large-footprint industrial buildings", "Logistics centres"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES DE PARED ----------
  {
    id: "bp-600",
    categoria: "ventiladores-pared",
    nombre: "BP 600",
    resumen: "Ventilador industrial de pared, entrada de gama.",
    resumenEn: "Entry-level industrial wall fan.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/BP600-1024x1024.avif",
    pvp: 1080,
    sageTools: "1022001",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de pared para ventilación forzada en espacios que no retienen el frío de un climatizador: naves con puertas abiertas, talleres con ventilación natural o almacenes con tráfico constante.",
    descripcionEn: "Wall fan for forced ventilation in spaces that can't hold the cold air from a climate control unit: buildings with open doors, workshops with natural ventilation, or warehouses with constant traffic.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
    ],
    specsEn: [
      { label: "Type", value: "Industrial wall fan" },
    ],
    aplicaciones: ["Talleres", "Almacenes", "Naves con ventilación natural"],
    aplicacionesEn: ["Workshops", "Warehouses", "Buildings with natural ventilation"],
    variantes: null,
  },
  {
    id: "bp-900",
    categoria: "ventiladores-pared",
    nombre: "BP 900",
    resumen: "Ventilador industrial de pared de mayor caudal que el BP 600.",
    resumenEn: "Industrial wall fan with higher airflow than the BP 600.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/BP900-1024x1024.avif",
    pvp: 1187,
    sageTools: "1022002",
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor caudal de la serie BP, para espacios de pared donde se necesita mover más volumen de aire.",
    descripcionEn: "A higher-airflow model from the BP series, for wall-mounted applications where more air volume needs to be moved.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
    ],
    specsEn: [
      { label: "Type", value: "Industrial wall fan" },
    ],
    aplicaciones: ["Talleres", "Almacenes", "Naves con ventilación natural"],
    aplicacionesEn: ["Workshops", "Warehouses", "Buildings with natural ventilation"],
    variantes: null,
  },
  {
    id: "bp-1200",
    categoria: "ventiladores-pared",
    nombre: "BP 1200",
    resumen: "El modelo de mayor caudal de la serie de ventiladores de pared BP.",
    resumenEn: "The highest-airflow unit in the BP wall fan series.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/BP1200-1024x1024.avif",
    pvp: 1329,
    sageTools: "1022003",
    gid: null,
    destacado: false,
    descripcion: "El equipo de mayores prestaciones de la serie BP, para naves y espacios de pared que requieren el máximo caudal de ventilación forzada.",
    descripcionEn: "The top-performing model in the BP wall fan series, for buildings and wall-mounted applications that need maximum forced-ventilation airflow.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
    ],
    specsEn: [
      { label: "Type", value: "Industrial wall fan" },
    ],
    aplicaciones: ["Naves industriales", "Almacenes de gran superficie"],
    aplicacionesEn: ["Industrial buildings", "Large-footprint warehouses"],
    variantes: null,
  },
  // ---------- ROPA TÉRMICA Y REFRIGERANTE ----------
  {
    id: "bw05",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante BW-05",
    resumen: "Tecnología evaporativa: se activa con agua y refresca hasta 15 °C bajo la temperatura ambiente.",
    resumenEn: "Evaporative technology: activated with water, cools up to 15 °C below ambient.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/01/Chaleco-BW05-1024x1024.avif",
    pvp: 59.95,
    sageTools: "1090011",
    gid: "5287.1",
    destacado: true,
    descripcion: "Chaleco de tecnología evaporativa: se sumerge en agua uno o dos minutos y el tejido técnico libera la humedad de forma progresiva. Especialmente eficaz en exteriores con flujo de aire.",
    descripcionEn: "Evaporative-technology vest: soak it in water for one or two minutes and the technical fabric releases moisture gradually. Especially effective outdoors with airflow.",
    specs: [
      { label: "Tecnología", value: "Evaporativa (tejido técnico + agua)" },
      { label: "Efecto de enfriamiento", value: "Hasta 15 °C por debajo de la temperatura ambiente" },
      { label: "Autonomía por activación", value: "4–8 horas" },
      { label: "Reactivación", value: "Volver a mojar el tejido" },
      { label: "Talla", value: "Única" },
    ],
    specsEn: [
      { label: "Technology", value: "Evaporative (technical fabric + water)" },
      { label: "Cooling effect", value: "Up to 15 °C below ambient temperature" },
      { label: "Runtime per activation", value: "4–8 horas" },
      { label: "Reactivation", value: "Re-soak the fabric" },
      { label: "Size", value: "One size" },
    ],
    aplicaciones: ["Construcción y obras públicas", "Agricultura", "Logística al aire libre", "Servicios municipales y limpieza viaria"],
    aplicacionesEn: ["Construction and public works", "Agriculture", "Outdoor logistics", "Municipal services and street cleaning"],
    variantes: null,
  },
  {
    id: "bw08",
    categoria: "ropa-termica",
    nombre: "Chaleco reflectante refrigerante BW08",
    resumen: "Misma tecnología evaporativa que el BW-05, con bandas reflectantes de alta visibilidad.",
    resumenEn: "Same evaporative technology as the BW-05, with high-visibility reflective bands.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Productoo-1024x1024.avif",
    pvp: 59.95,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Chaleco con bandas reflectantes de alta visibilidad para entornos que lo requieren, manteniendo la misma tecnología evaporativa y transpirable de la gama BW.",
    descripcionEn: "Vest with high-visibility reflective bands for environments that require them, keeping the same evaporative, breathable technology as the BW range.",
    specs: [
      { label: "Tecnología", value: "Evaporativa (tejido técnico + agua)" },
      { label: "Efecto de enfriamiento", value: "Hasta 15 °C por debajo de la temperatura ambiente" },
      { label: "Autonomía por activación", value: "4–8 horas" },
      { label: "Extra", value: "Bandas reflectantes de alta visibilidad" },
    ],
    specsEn: [
      { label: "Technology", value: "Evaporative (technical fabric + water)" },
      { label: "Cooling effect", value: "Up to 15 °C below ambient temperature" },
      { label: "Runtime per activation", value: "4–8 horas" },
      { label: "Extra", value: "High-visibility reflective bands" },
    ],
    aplicaciones: ["Obras públicas y vía pública", "Transporte y reparto", "Trabajo nocturno o con baja visibilidad"],
    aplicacionesEn: ["Public works and roadside work", "Transport and delivery", "Night work or low-visibility conditions"],
    variantes: [
      { color: "Amarillo", talla: "SM", sageTools: "1090012" },
      { color: "Amarillo", talla: "ML", sageTools: "1090013" },
      { color: "Amarillo", talla: "2XL / 3XL", sageTools: "1090014" },
      { color: "Naranja", talla: "SM", sageTools: "1090015" },
      { color: "Naranja", talla: "ML", sageTools: "1090016" },
      { color: "Naranja", talla: "2XL / 3XL", sageTools: "1090017" },
    ],
  },
  {
    id: "bw01-pcm",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante PCM BW-01",
    resumen: "Placas de cambio de fase: frío estable y constante, sin humedad ni goteo.",
    resumenEn: "Phase-change plates: stable, constant cold with no moisture or dripping.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/modelo_BW_3.avif",
    pvp: 169.9,
    sageTools: "1090001",
    gid: "5287.4",
    destacado: false,
    descripcion: "Prenda con placas PCM (Phase Change Material) que absorben calor manteniendo una temperatura constante y predefinida durante el cambio de estado. Ideal para interiores sin apenas flujo de aire o bajo ropa de protección.",
    descripcionEn: "Garment with PCM (Phase Change Material) plates that absorb heat while holding a constant, preset temperature during the phase change. Ideal for indoor spaces with little airflow or under protective clothing.",
    specs: [
      { label: "Tecnología", value: "Placas PCM (material de cambio de fase)" },
      { label: "Regeneración en nevera (4–10 °C)", value: "2–4 horas" },
      { label: "Regeneración en congelador", value: "Más rápida" },
      { label: "Talla", value: "Única" },
    ],
    specsEn: [
      { label: "Technology", value: "PCM plates (phase change material)" },
      { label: "Fridge recharge (4–10 °C)", value: "2–4 horas" },
      { label: "Freezer recharge", value: "Faster" },
      { label: "Size", value: "One size" },
    ],
    aplicaciones: ["Interiores sin flujo de aire", "Bajo ropa de protección (EPI)", "Hornos, fundición, soldadura"],
    aplicacionesEn: ["Indoor spaces with no airflow", "Under PPE / protective clothing", "Furnaces, foundries, welding"],
    variantes: null,
  },
  {
    id: "bw04",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante BW-04",
    resumen: "Chaleco refrigerante de la gama BW, disponible en varias tallas.",
    resumenEn: "Cooling vest from the BW range, available in several sizes.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/modelo_BW_5.avif",
    pvp: 59.95,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Chaleco refrigerante de tecnología evaporativa de la gama Blizzcool, en versión sin bandas reflectantes.",
    descripcionEn: "Evaporative-technology cooling vest from the Blizzcool range, in the version without reflective bands.",
    specs: [
      { label: "Tecnología", value: "Evaporativa (tejido técnico + agua)" },
      { label: "Efecto de enfriamiento", value: "Hasta 15 °C por debajo de la temperatura ambiente" },
    ],
    specsEn: [
      { label: "Technology", value: "Evaporative (technical fabric + water)" },
      { label: "Cooling effect", value: "Up to 15 °C below ambient temperature" },
    ],
    aplicaciones: ["Construcción y obras públicas", "Agricultura", "Logística al aire libre"],
    aplicacionesEn: ["Construction and public works", "Agriculture", "Outdoor logistics"],
    variantes: [
      { color: null, talla: "M", sageTools: "1090007" },
      { color: null, talla: "L", sageTools: "1090008" },
      { color: null, talla: "XL", sageTools: "1090009" },
      { color: null, talla: "2XL", sageTools: "1090010" },
    ],
  },
  {
    id: "bw02-pcm",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante PCM BW-02 + Pack",
    resumen: "Chaleco PCM con pack de placas incluido, talla única.",
    resumenEn: "PCM vest with plate pack included, one size.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Chaleco-BW02-1024x1024.avif",
    pvp: 149.9,
    sageTools: "1090018",
    gid: null,
    destacado: false,
    descripcion: "Versión de chaleco PCM que incluye pack de placas de recambio, para alternar ciclos de refrigeración sin interrumpir el turno de trabajo.",
    descripcionEn: "PCM vest version that includes a spare plate pack, to alternate cooling cycles without interrupting the work shift.",
    specs: [
      { label: "Tecnología", value: "Placas PCM (material de cambio de fase)" },
      { label: "Incluye", value: "Pack de placas de recambio" },
      { label: "Talla", value: "Única" },
    ],
    specsEn: [
      { label: "Technology", value: "PCM plates (phase change material)" },
      { label: "Includes", value: "Spare plate pack" },
      { label: "Size", value: "One size" },
    ],
    aplicaciones: ["Interiores sin flujo de aire", "Bajo ropa de protección (EPI)"],
    aplicacionesEn: ["Indoor spaces with no airflow", "Under PPE / protective clothing"],
    variantes: null,
  },
  // ---------- RECAMBIOS Y POST-VENTA ----------
  {
    id: "bomba-bc200-bc290",
    categoria: "recambios",
    nombre: "Bomba enfriador BC200 / BC290",
    resumen: "Recambio de bomba de agua para los enfriadores evaporativos BC200 y BC290.",
    resumenEn: "Replacement water pump for the BC200 and BC290 evaporative coolers.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Bomba-de-Agua-1024x1024.avif",
    pvp: 59.9,
    sageTools: "1019001",
    gid: "5176.15",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el circuito de agua de los enfriadores evaporativos BC200 y BC290.",
    descripcionEn: "Original Blizzcool spare part for the water circuit of the BC200 and BC290 evaporative coolers.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200, BC290" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "bomba-bc395",
    categoria: "recambios",
    nombre: "Bomba enfriador BC395",
    resumen: "Recambio de bomba de agua para el enfriador evaporativo BC395.",
    resumenEn: "Replacement water pump for the BC395 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Bomba-de-Agua-1024x1024.avif",
    pvp: 72.25,
    sageTools: "1019002",
    gid: "5176.14",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el circuito de agua del enfriador evaporativo BC395.",
    descripcionEn: "Original Blizzcool spare part for the water circuit of the BC395 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "filtros-bc200",
    categoria: "recambios",
    nombre: "Paquete de filtros BC200 (3 uds.)",
    resumen: "Recambio de filtros para el enfriador evaporativo BC200.",
    resumenEn: "Replacement filters for the BC200 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Filtro2-1-1024x1024.avif",
    pvp: 93.25,
    sageTools: "1018001",
    gid: "5176.18",
    destacado: false,
    descripcion: "Paquete de 3 filtros de recambio originales Blizzcool para el enfriador evaporativo BC200.",
    descripcionEn: "Pack of 3 original Blizzcool replacement filters for the BC200 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC200" },
      { label: "Unidades", value: "3" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200" },
      { label: "Units", value: "3" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "filtros-bc290",
    categoria: "recambios",
    nombre: "Paquete de filtros BC290 (3 uds.)",
    resumen: "Recambio de filtros para el enfriador evaporativo BC290.",
    resumenEn: "Replacement filters for the BC290 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Filtro2-1-1024x1024.avif",
    pvp: 104,
    sageTools: "1018002",
    gid: "5176.12",
    destacado: false,
    descripcion: "Paquete de 3 filtros de recambio originales Blizzcool para el enfriador evaporativo BC290.",
    descripcionEn: "Pack of 3 original Blizzcool replacement filters for the BC290 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC290" },
      { label: "Unidades", value: "3" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC290" },
      { label: "Units", value: "3" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "filtros-bc395",
    categoria: "recambios",
    nombre: "Paquete de filtros BC395 (3 uds.)",
    resumen: "Recambio de filtros para el enfriador evaporativo BC395.",
    resumenEn: "Replacement filters for the BC395 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Filtro2-1-1024x1024.avif",
    pvp: 147.35,
    sageTools: "1018003",
    gid: "5176.13",
    destacado: false,
    descripcion: "Paquete de 3 filtros de recambio originales Blizzcool para el enfriador evaporativo BC395.",
    descripcionEn: "Pack of 3 original Blizzcool replacement filters for the BC395 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC395" },
      { label: "Unidades", value: "3" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC395" },
      { label: "Units", value: "3" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "generador-anion",
    categoria: "recambios",
    nombre: "Generador de anión",
    resumen: "Recambio del generador de aniones para enfriadores evaporativos Blizzcool.",
    resumenEn: "Replacement anion generator for Blizzcool evaporative coolers.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Generador-de-Anion-1024x1024.avif",
    pvp: 59.9,
    sageTools: "1019010",
    gid: "5176.16",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el sistema de generación de aniones incorporado en los enfriadores evaporativos.",
    descripcionEn: "Original Blizzcool spare part for the anion-generation system built into the evaporative coolers.",
    specs: [
      { label: "Tipo", value: "Recambio — generador de aniones" },
    ],
    specsEn: [
      { label: "Type", value: "Spare part — anion generator" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "panel-control-bc",
    categoria: "recambios",
    nombre: "Panel de control BC200 / BC290 / BC395",
    resumen: "Recambio de panel de control para toda la gama de enfriadores BC.",
    resumenEn: "Replacement control panel for the full BC cooler range.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Panel-de-Control-Frente-1024x1024.avif",
    pvp: 59.95,
    sageTools: "1019003",
    gid: "5176.23",
    destacado: false,
    descripcion: "Panel de control de recambio original Blizzcool, compatible con los tres modelos de la gama de enfriadores evaporativos BC.",
    descripcionEn: "Original Blizzcool replacement control panel, compatible with all three models in the BC evaporative cooler range.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290, BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200, BC290, BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "helice-bc200",
    categoria: "recambios",
    nombre: "Hélice enfriador BC200",
    resumen: "Recambio de hélice para el enfriador evaporativo BC200.",
    resumenEn: "Replacement fan blade for the BC200 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Helice-BC200-1-1024x1024.avif",
    pvp: 28.5,
    sageTools: "1019004",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC200.",
    descripcionEn: "Original Blizzcool spare part for the BC200 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC200" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "helice-bc290",
    categoria: "recambios",
    nombre: "Hélice enfriador BC290",
    resumen: "Recambio de hélice para el enfriador evaporativo BC290.",
    resumenEn: "Replacement fan blade for the BC290 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Helice-BC200-1-1024x1024.avif",
    pvp: 56.35,
    sageTools: "1019005",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC290.",
    descripcionEn: "Original Blizzcool spare part for the BC290 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC290" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC290" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "helice-bc395",
    categoria: "recambios",
    nombre: "Hélice enfriador BC395",
    resumen: "Recambio de hélice para el enfriador evaporativo BC395.",
    resumenEn: "Replacement fan blade for the BC395 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Helice-BC200-1-1024x1024.avif",
    pvp: 78.48,
    sageTools: "1019006",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC395.",
    descripcionEn: "Original Blizzcool spare part for the BC395 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "parrilla-bc200",
    categoria: "recambios",
    nombre: "Parrilla enfriador BC200",
    resumen: "Recambio de parrilla para el enfriador evaporativo BC200.",
    resumenEn: "Replacement grille for the BC200 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Rejilla-1024x1024.avif",
    pvp: 22.8,
    sageTools: "1019007",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC200.",
    descripcionEn: "Original Blizzcool spare part for the BC200 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC200" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC200" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "parrilla-bc290",
    categoria: "recambios",
    nombre: "Parrilla enfriador BC290",
    resumen: "Recambio de parrilla para el enfriador evaporativo BC290.",
    resumenEn: "Replacement grille for the BC290 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Rejilla-1024x1024.avif",
    pvp: 40.25,
    sageTools: "1019008",
    gid: "5176.8",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC290.",
    descripcionEn: "Original Blizzcool spare part for the BC290 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC290" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC290" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "parrilla-bc395",
    categoria: "recambios",
    nombre: "Parrilla enfriador BC395",
    resumen: "Recambio de parrilla para el enfriador evaporativo BC395.",
    resumenEn: "Replacement grille for the BC395 evaporative cooler.",
    imagen: "https://blizzcool.es/wp-content/uploads/2026/02/Rejilla-1024x1024.avif",
    pvp: 50.49,
    sageTools: "1019009",
    gid: "5176.9",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC395.",
    descripcionEn: "Original Blizzcool spare part for the BC395 evaporative cooler.",
    specs: [
      { label: "Compatible con", value: "BC395" },
    ],
    specsEn: [
      { label: "Compatible with", value: "BC395" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
  {
    id: "pack-pc01",
    categoria: "recambios",
    nombre: "Pack refrigerante PC01 (4 uds.)",
    resumen: "Pack de 4 placas refrigerantes de recambio para chalecos PCM.",
    resumenEn: "Pack of 4 replacement PCM cooling plates for cooling vests.",
    imagen: "https://blizzcool.es/wp-content/uploads/2025/12/Placas-de-Hielo-1024x825.avif",
    pvp: 109.9,
    sageTools: "1090051",
    gid: "5287.3",
    destacado: false,
    descripcion: "Pack de 4 placas PCM de recambio, compatibles con los chalecos refrigerantes PCM de la gama Blizzcool, para disponer de juegos extra y alternar ciclos sin interrumpir el turno.",
    descripcionEn: "Pack of 4 replacement PCM plates, compatible with the Blizzcool PCM cooling vest range, to keep a spare set and alternate cycles without interrupting the shift.",
    specs: [
      { label: "Unidades", value: "4" },
      { label: "Compatible con", value: "Chalecos refrigerantes PCM Blizzcool" },
    ],
    specsEn: [
      { label: "Units", value: "4" },
      { label: "Compatible with", value: "Blizzcool PCM cooling vests" },
    ],
    aplicaciones: [],
    aplicacionesEn: [],
    variantes: null,
  },
];
