/**
 * CATÁLOGO BLIZZCOOL — fichero de datos
 * ---------------------------------------------------
 * Precios: columna PVP de la tarifa oficial (TARIFA_BLIZZCOOL_NETOS_Y_REVENDEDORES.xlsx),
 * siempre SIN IVA. El sitio calcula el 21% de IVA con el interruptor de la cabecera.
 *
 * Cómo alimentar este fichero:
 * - imagen: ruta a la foto del equipo (ej. "img/ac-1900-1.jpg"). Déjalo en null si aún no hay foto.
 * - pvp: precio de venta al público SIN IVA (número). Es el precio de referencia de la tarifa.
 * - specs: lista de { label, value } — lo que sale en la ficha técnica.
 * - sageTools / gid: códigos internos de la tarifa, se muestran como referencia en la ficha.
 * - No borres ningún campo aunque esté vacío: usa null o "" para no romper la página.
 * - Para añadir un producto nuevo, copia un bloque entero y cambia el "id" (debe ser único, sin espacios).
 */

const CATEGORIAS = [
  { id: "aire-acondicionado", nombre: "Aire acondicionado industrial portátil" },
  { id: "enfriadores-evaporativos", nombre: "Enfriadores evaporativos industriales" },
  { id: "nebulizadores", nombre: "Nebulizadores industriales" },
  { id: "ventiladores-techo", nombre: "Ventiladores industriales de techo" },
  { id: "ventiladores-portatiles", nombre: "Ventiladores industriales portátiles" },
  { id: "ventiladores-pared", nombre: "Ventiladores industriales de pared" },
  { id: "ropa-termica", nombre: "Ropa térmica y refrigerante" },
  { id: "recambios", nombre: "Recambios y post-venta" },
];

const PRODUCTOS = [
  // ---------- AIRE ACONDICIONADO INDUSTRIAL PORTÁTIL ----------
  {
    id: "ac-1900-1",
    categoria: "aire-acondicionado",
    nombre: "AC-1900/1",
    resumen: "Spot cooler compacto para espacios medianos, oficinas y locales sin obra.",
    imagen: null,
    pvp: 695,
    sageTools: "1030001",
    gid: "5252.5",
    destacado: true,
    descripcion: "Aire acondicionado portátil por compresor, listo para enfriar con un simple enchufe estándar y un tubo de evacuación al exterior. Pensado para locales comerciales, oficinas en alquiler o como equipo de emergencia cuando falla un sistema fijo.",
    specs: [
      { label: "Capacidad frigorífica", value: "Aprox. 2.000 frigorías" },
      { label: "Tipo", value: "Spot cooler por compresor" },
      { label: "Instalación", value: "Sin obra — enchufe + tubo de evacuación" },
      { label: "Movilidad", value: "Con ruedas" },
      { label: "Temperatura ambiente de trabajo", value: "Hasta 45 °C" },
    ],
    aplicaciones: ["Locales comerciales y oficinas en alquiler", "Salas de servidores pequeñas", "Equipo de emergencia ante avería de climatización fija", "Eventos y ferias"],
    variantes: null,
  },
  {
    id: "ac-2700-1",
    categoria: "aire-acondicionado",
    nombre: "AC-2700/1",
    resumen: "Spot cooler intermedio para talleres y locales de tamaño medio.",
    imagen: null,
    pvp: 890,
    sageTools: "1030002",
    gid: "5252.1",
    destacado: false,
    descripcion: "Segundo escalón de la gama de spot coolers Blizzcool, entre el AC-1900/1 y el AC-3500/2. Refrigeración por compresor, portátil y sin necesidad de instalación fija.",
    specs: [
      { label: "Capacidad frigorífica", value: "Aprox. 2.700 frigorías" },
      { label: "Tipo", value: "Spot cooler por compresor" },
      { label: "Instalación", value: "Sin obra — enchufe + tubo de evacuación" },
      { label: "Movilidad", value: "Con ruedas" },
      { label: "Temperatura ambiente de trabajo", value: "Hasta 45 °C" },
    ],
    aplicaciones: ["Talleres y locales comerciales medianos", "Salas técnicas", "Eventos y ferias"],
    variantes: null,
  },
  {
    id: "ac-3500-2",
    categoria: "aire-acondicionado",
    nombre: "AC-3500/2",
    resumen: "3.500 frigorías para talleres, almacenes y fábricas de tamaño medio.",
    imagen: null,
    pvp: 1165,
    sageTools: "1030003",
    gid: "5252.2",
    destacado: true,
    descripcion: "Sistema de refrigeración por compresor de alto rendimiento y bajo consumo, diseñado para trabajar de forma continua en entornos exigentes. Portátil, con ruedas y sin necesidad de instalación fija.",
    specs: [
      { label: "Capacidad frigorífica", value: "3.500 frigorías" },
      { label: "Tipo", value: "Spot cooler por compresor" },
      { label: "Refrigerante", value: "Ecológico" },
      { label: "Movilidad", value: "Con ruedas" },
      { label: "Temperatura ambiente de trabajo", value: "Hasta 45 °C" },
    ],
    aplicaciones: ["Talleres y almacenes", "Fábricas", "Eventos, ferias y exposiciones"],
    variantes: null,
  },
  {
    id: "ac-5300-3",
    categoria: "aire-acondicionado",
    nombre: "AC-5300/3",
    resumen: "La referencia de mayor capacidad de la gama, para grandes superficies.",
    imagen: null,
    pvp: 1990,
    sageTools: "1030004",
    gid: "5252.3",
    destacado: false,
    descripcion: "El modelo de mayores prestaciones de la gama de spot coolers Blizzcool. Refrigeración por compresor de alto rendimiento para naves y locales de gran superficie, operativo el mismo día sin obra ni permisos.",
    specs: [
      { label: "Capacidad frigorífica", value: "5.300 frigorías" },
      { label: "Tipo", value: "Spot cooler por compresor" },
      { label: "Instalación", value: "Sin obra — enchufe + tubo de evacuación" },
      { label: "Movilidad", value: "Con ruedas" },
      { label: "Temperatura ambiente de trabajo", value: "Hasta 45 °C" },
    ],
    aplicaciones: ["Naves industriales de gran superficie", "Salas de servidores y centros de datos", "Locales comerciales grandes"],
    variantes: null,
  },
  // ---------- ENFRIADORES EVAPORATIVOS INDUSTRIALES ----------
  {
    id: "bc-200",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 200",
    resumen: "Enfriador evaporativo de entrada de gama, para espacios medianos.",
    imagen: null,
    pvp: 1540,
    sageTools: "1010001",
    gid: "5176.7",
    destacado: false,
    descripcion: "Equipo de climatización por evaporación de agua: aspira aire caliente, lo hace pasar por paneles húmedos y lo devuelve más frío, sin gases refrigerantes ni compresor. Consumo eléctrico muy inferior al de un aire acondicionado equivalente.",
    specs: [
      { label: "Tipo", value: "Enfriador evaporativo" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    aplicaciones: ["Talleres y almacenes medianos", "Locales comerciales", "Espacios deportivos"],
    variantes: null,
  },
  {
    id: "bc-290",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 290",
    resumen: "Enfriador evaporativo de gama media, mayor caudal que el BC 200.",
    imagen: null,
    pvp: 1815,
    sageTools: "1010002",
    gid: "5176.2",
    destacado: false,
    descripcion: "Equipo de climatización por evaporación de agua, un escalón por encima del BC 200 en caudal de aire. Sin gases refrigerantes ni compresor, con un coste operativo muy inferior al del aire acondicionado tradicional.",
    specs: [
      { label: "Tipo", value: "Enfriador evaporativo" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    aplicaciones: ["Naves y talleres", "Almacenes y centros logísticos", "Terrazas de hostelería"],
    variantes: null,
  },
  {
    id: "bc-395",
    categoria: "enfriadores-evaporativos",
    nombre: "BC 395",
    resumen: "Enfriador evaporativo de gran caudal para naves y espacios amplios.",
    imagen: null,
    pvp: 2189,
    sageTools: "1010003",
    gid: "5176.3",
    destacado: true,
    descripcion: "Equipo de climatización por evaporación de agua: aspira aire caliente, lo hace pasar por paneles húmedos y lo devuelve hasta 15 °C más frío, sin gases refrigerantes ni compresor. Consumo eléctrico muy inferior al de un aire acondicionado equivalente.",
    specs: [
      { label: "Caudal de aire", value: "Hasta 345 m³/min" },
      { label: "Reducción de temperatura", value: "Entre 12 y 15 °C en condiciones óptimas" },
      { label: "Consumo estimado", value: "0,5–3 kW/h según modelo" },
      { label: "Refrigerante", value: "Sin gases — solo agua y aire" },
      { label: "Extra", value: "Sistema anti-bacterias integrado" },
      { label: "Clima recomendado", value: "Seco — humedad relativa por debajo del 60%" },
    ],
    aplicaciones: ["Naves industriales y de producción", "Talleres mecánicos y de carrocería", "Almacenes y centros logísticos", "Gimnasios y espacios deportivos", "Terrazas de hostelería"],
    variantes: null,
  },
  // ---------- NEBULIZADORES INDUSTRIALES ----------
  {
    id: "bsm-160l",
    categoria: "nebulizadores",
    nombre: "BSM160L",
    resumen: "Nebulizador de alto caudal con depósito de 160 litros para jornadas completas.",
    imagen: null,
    pvp: 2490.35,
    sageTools: "1040001",
    gid: "5176.24",
    destacado: true,
    descripcion: "Sistema de nebulización de gota fina (por debajo de 10 micras) que garantiza evaporación completa sin mojar personas ni superficies. Funciona con un simple enchufe estándar, sin instalación eléctrica específica.",
    specs: [
      { label: "Capacidad de depósito", value: "160 L" },
      { label: "Tamaño de gota", value: "Menos de 10 micras" },
      { label: "Alimentación", value: "Enchufe estándar" },
      { label: "Rendimiento óptimo", value: "Humedad relativa por debajo del 70–75%" },
    ],
    aplicaciones: ["Naves industriales y logística", "Hostelería y terrazas", "Eventos deportivos y culturales"],
    variantes: null,
  },
  {
    id: "bsm-380l",
    categoria: "nebulizadores",
    nombre: "BSM380L",
    resumen: "Máxima autonomía de la gama: depósito de 380 litros para eventos y grandes espacios.",
    imagen: null,
    pvp: 2992.28,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor depósito de la gama de nebulizadores industriales Blizzcool, pensada para jornadas o eventos completos sin recargas, cubriendo superficies de hasta 250 m² por equipo.",
    specs: [
      { label: "Capacidad de depósito", value: "380 L" },
      { label: "Cobertura", value: "Hasta 250 m² por equipo" },
      { label: "Tamaño de gota", value: "Menos de 10 micras" },
      { label: "Alimentación", value: "Enchufe estándar" },
    ],
    aplicaciones: ["Pabellones y campus deportivos sin climatización centralizada", "Eventos y ferias exteriores", "Zonas VIP y áreas de calentamiento"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES DE TECHO ----------
  {
    id: "fam240",
    categoria: "ventiladores-techo",
    nombre: "BW FAM240 · Ø2400 mm",
    resumen: "Ventilador de techo de gran diámetro, entrada de gama de la serie FAM.",
    imagen: null,
    pvp: 1090,
    sageTools: "1021001",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad. Mueve grandes volúmenes de aire con un consumo mucho menor que un equipo de climatización de potencia equivalente, sin necesidad de enfriar todo el volumen de la nave.",
    specs: [
      { label: "Diámetro", value: "2.400 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Complemento de climatización existente"],
    variantes: null,
  },
  {
    id: "fam300",
    categoria: "ventiladores-techo",
    nombre: "BW FAM300 · Ø3000 mm",
    resumen: "Ventilador de techo de la serie FAM, un escalón por encima del FAM240.",
    imagen: null,
    pvp: 1120,
    sageTools: "1021002",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad, con mayor diámetro que el FAM240 para cubrir superficies más amplias.",
    specs: [
      { label: "Diámetro", value: "3.000 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Complemento de climatización existente"],
    variantes: null,
  },
  {
    id: "fam370",
    categoria: "ventiladores-techo",
    nombre: "BW FAM370 · Ø3700 mm",
    resumen: "Ventilador de techo de gran diámetro para naves amplias.",
    imagen: null,
    pvp: 1190,
    sageTools: "1021003",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de techo de alto volumen y baja velocidad, pensado para espacios de mayor superficie que los modelos FAM240 y FAM300.",
    specs: [
      { label: "Diámetro", value: "3.700 mm" },
      { label: "Tipo", value: "Techo, alto volumen / baja velocidad" },
    ],
    aplicaciones: ["Naves industriales de gran altura", "Almacenes y centros logísticos"],
    variantes: null,
  },
  {
    id: "fam430",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM430 · Ø4300 mm",
    resumen: "Ventilador de techo de la serie profesional BWP, gran diámetro.",
    imagen: null,
    pvp: 1882,
    sageTools: "1021004",
    gid: null,
    destacado: false,
    descripcion: "Versión de la serie profesional BWP, con mayor diámetro y caudal que la serie FAM estándar. Pensado para naves de gran volumen.",
    specs: [
      { label: "Diámetro", value: "4.300 mm" },
      { label: "Serie", value: "BWP (profesional)" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Centros logísticos"],
    variantes: null,
  },
  {
    id: "fam500",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM500 · Ø5000 mm",
    resumen: "Ventilador de techo de la serie profesional BWP, gran diámetro.",
    imagen: null,
    pvp: 1882,
    sageTools: "1021005",
    gid: null,
    destacado: false,
    descripcion: "Versión de la serie profesional BWP con 5.000 mm de diámetro, para cubrir grandes superficies con un único equipo.",
    specs: [
      { label: "Diámetro", value: "5.000 mm" },
      { label: "Serie", value: "BWP (profesional)" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Centros logísticos"],
    variantes: null,
  },
  {
    id: "fam610",
    categoria: "ventiladores-techo",
    nombre: "BWP FAM610 · Ø6100 mm",
    resumen: "El mayor diámetro de la serie profesional BWP.",
    imagen: null,
    pvp: 2679,
    sageTools: "1021006",
    gid: null,
    destacado: false,
    descripcion: "El modelo de mayor diámetro de la serie BWP, para las naves y espacios de mayor superficie de la gama de ventilación de techo Blizzcool.",
    specs: [
      { label: "Diámetro", value: "6.100 mm" },
      { label: "Serie", value: "BWP (profesional)" },
    ],
    aplicaciones: ["Naves industriales de gran volumen", "Pabellones y grandes superficies"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES PORTÁTILES ----------
  {
    id: "gd-120",
    categoria: "ventiladores-portatiles",
    nombre: "GD 120 · Ø1200 mm",
    resumen: "Ventilador móvil de suelo, motor BLDC de bajo consumo.",
    imagen: null,
    pvp: 1350,
    sageTools: "1020001",
    gid: null,
    destacado: true,
    descripcion: "Ventilador portátil diseñado desde el origen para mover el aire en espacios de cientos o miles de m², no doméstico reconvertido. La tecnología BLDC (motor de corriente continua sin escobillas) ofrece caudales elevados con consumo mínimo.",
    specs: [
      { label: "Diámetro", value: "1.200 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales — reubicación sin herramientas" },
    ],
    aplicaciones: ["Naves con puertas abiertas o ventilación natural", "Talleres", "Almacenes con tráfico constante de mercancía"],
    variantes: null,
  },
  {
    id: "gd-150",
    categoria: "ventiladores-portatiles",
    nombre: "GD 150 · Ø1500 mm",
    resumen: "Ventilador móvil de mayor diámetro que el GD 120.",
    imagen: null,
    pvp: 1650,
    sageTools: "1020002",
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor diámetro de la serie GD, con motor BLDC de bajo consumo y ruedas industriales para reubicación inmediata.",
    specs: [
      { label: "Diámetro", value: "1.500 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales" },
    ],
    aplicaciones: ["Naves y almacenes de mayor superficie", "Talleres"],
    variantes: null,
  },
  {
    id: "gd-200",
    categoria: "ventiladores-portatiles",
    nombre: "GD 200 · Ø2000 mm",
    resumen: "El modelo de mayor diámetro de la serie GD portátil.",
    imagen: null,
    pvp: 1890,
    sageTools: "1020003",
    gid: null,
    destacado: false,
    descripcion: "El equipo de mayor caudal de la serie de ventiladores portátiles GD, para espacios de gran superficie que necesitan movilidad total.",
    specs: [
      { label: "Diámetro", value: "2.000 mm" },
      { label: "Motor", value: "BLDC sin escobillas" },
      { label: "Movilidad", value: "Ruedas industriales" },
    ],
    aplicaciones: ["Naves industriales de gran superficie", "Centros logísticos"],
    variantes: null,
  },
  // ---------- VENTILADORES INDUSTRIALES DE PARED ----------
  {
    id: "bp-600",
    categoria: "ventiladores-pared",
    nombre: "BP 600",
    resumen: "Ventilador industrial de pared, entrada de gama.",
    imagen: null,
    pvp: 1080,
    sageTools: "1022001",
    gid: null,
    destacado: false,
    descripcion: "Ventilador de pared para ventilación forzada en espacios que no retienen el frío de un climatizador: naves con puertas abiertas, talleres con ventilación natural o almacenes con tráfico constante.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
    ],
    aplicaciones: ["Talleres", "Almacenes", "Naves con ventilación natural"],
    variantes: null,
  },
  {
    id: "bp-900",
    categoria: "ventiladores-pared",
    nombre: "BP 900",
    resumen: "Ventilador industrial de pared de mayor caudal que el BP 600.",
    imagen: null,
    pvp: 1187,
    sageTools: "1022002",
    gid: null,
    destacado: false,
    descripcion: "Versión de mayor caudal de la serie BP, para espacios de pared donde se necesita mover más volumen de aire.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
    ],
    aplicaciones: ["Talleres", "Almacenes", "Naves con ventilación natural"],
    variantes: null,
  },
  {
    id: "bp-1200",
    categoria: "ventiladores-pared",
    nombre: "BP 1200",
    resumen: "El modelo de mayor caudal de la serie de ventiladores de pared BP.",
    imagen: null,
    pvp: 1329,
    sageTools: "1022003",
    gid: null,
    destacado: false,
    descripcion: "El equipo de mayores prestaciones de la serie BP, para naves y espacios de pared que requieren el máximo caudal de ventilación forzada.",
    specs: [
      { label: "Tipo", value: "Ventilador industrial de pared" },
    ],
    aplicaciones: ["Naves industriales", "Almacenes de gran superficie"],
    variantes: null,
  },
  // ---------- ROPA TÉRMICA Y REFRIGERANTE ----------
  {
    id: "bw05",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante BW-05",
    resumen: "Tecnología evaporativa: se activa con agua y refresca hasta 15 °C bajo la temperatura ambiente.",
    imagen: null,
    pvp: 59.95,
    sageTools: "1090011",
    gid: "5287.1",
    destacado: true,
    descripcion: "Chaleco de tecnología evaporativa: se sumerge en agua uno o dos minutos y el tejido técnico libera la humedad de forma progresiva. Especialmente eficaz en exteriores con flujo de aire.",
    specs: [
      { label: "Tecnología", value: "Evaporativa (tejido técnico + agua)" },
      { label: "Efecto de enfriamiento", value: "Hasta 15 °C por debajo de la temperatura ambiente" },
      { label: "Autonomía por activación", value: "4–8 horas" },
      { label: "Reactivación", value: "Volver a mojar el tejido" },
      { label: "Talla", value: "Única" },
    ],
    aplicaciones: ["Construcción y obras públicas", "Agricultura", "Logística al aire libre", "Servicios municipales y limpieza viaria"],
    variantes: null,
  },
  {
    id: "bw08",
    categoria: "ropa-termica",
    nombre: "Chaleco reflectante refrigerante BW08",
    resumen: "Misma tecnología evaporativa que el BW-05, con bandas reflectantes de alta visibilidad.",
    imagen: null,
    pvp: 59.95,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Chaleco con bandas reflectantes de alta visibilidad para entornos que lo requieren, manteniendo la misma tecnología evaporativa y transpirable de la gama BW.",
    specs: [
      { label: "Tecnología", value: "Evaporativa (tejido técnico + agua)" },
      { label: "Efecto de enfriamiento", value: "Hasta 15 °C por debajo de la temperatura ambiente" },
      { label: "Autonomía por activación", value: "4–8 horas" },
      { label: "Extra", value: "Bandas reflectantes de alta visibilidad" },
    ],
    aplicaciones: ["Obras públicas y vía pública", "Transporte y reparto", "Trabajo nocturno o con baja visibilidad"],
    variantes: [
      { color: "Amarillo", talla: "SM", sageTools: "1090012" },
      { color: "Amarillo", talla: "ML", sageTools: "1090013" },
      { color: "Amarillo", talla: "2XL / 3XL", sageTools: "1090014" },
      { color: "Naranja", talla: "SM", sageTools: "1090015" },
      { color: "Naranja", talla: "ML", sageTools: "1090016" },
      { color: "Naranja", talla: "2XL / 3XL", sageTools: "1090017" },
    ],
  },
  {
    id: "bw01-pcm",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante PCM BW-01",
    resumen: "Placas de cambio de fase: frío estable y constante, sin humedad ni goteo.",
    imagen: null,
    pvp: 169.9,
    sageTools: "1090001",
    gid: "5287.4",
    destacado: false,
    descripcion: "Prenda con placas PCM (Phase Change Material) que absorben calor manteniendo una temperatura constante y predefinida durante el cambio de estado. Ideal para interiores sin apenas flujo de aire o bajo ropa de protección.",
    specs: [
      { label: "Tecnología", value: "Placas PCM (material de cambio de fase)" },
      { label: "Regeneración en nevera (4–10 °C)", value: "2–4 horas" },
      { label: "Regeneración en congelador", value: "Más rápida" },
      { label: "Talla", value: "Única" },
    ],
    aplicaciones: ["Interiores sin flujo de aire", "Bajo ropa de protección (EPI)", "Hornos, fundición, soldadura"],
    variantes: null,
  },
  {
    id: "bw04",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante BW-04",
    resumen: "Chaleco refrigerante de la gama BW, disponible en varias tallas.",
    imagen: null,
    pvp: 59.95,
    sageTools: null,
    gid: null,
    destacado: false,
    descripcion: "Chaleco refrigerante de tecnología evaporativa de la gama Blizzcool, en versión sin bandas reflectantes.",
    specs: [
      { label: "Tecnología", value: "Evaporativa (tejido técnico + agua)" },
      { label: "Efecto de enfriamiento", value: "Hasta 15 °C por debajo de la temperatura ambiente" },
    ],
    aplicaciones: ["Construcción y obras públicas", "Agricultura", "Logística al aire libre"],
    variantes: [
      { color: null, talla: "M", sageTools: "1090007" },
      { color: null, talla: "L", sageTools: "1090008" },
      { color: null, talla: "XL", sageTools: "1090009" },
      { color: null, talla: "2XL", sageTools: "1090010" },
    ],
  },
  {
    id: "bw02-pcm",
    categoria: "ropa-termica",
    nombre: "Chaleco refrigerante PCM BW-02 + Pack",
    resumen: "Chaleco PCM con pack de placas incluido, talla única.",
    imagen: null,
    pvp: 149.9,
    sageTools: "1090018",
    gid: null,
    destacado: false,
    descripcion: "Versión de chaleco PCM que incluye pack de placas de recambio, para alternar ciclos de refrigeración sin interrumpir el turno de trabajo.",
    specs: [
      { label: "Tecnología", value: "Placas PCM (material de cambio de fase)" },
      { label: "Incluye", value: "Pack de placas de recambio" },
      { label: "Talla", value: "Única" },
    ],
    aplicaciones: ["Interiores sin flujo de aire", "Bajo ropa de protección (EPI)"],
    variantes: null,
  },
  // ---------- RECAMBIOS Y POST-VENTA ----------
  {
    id: "bomba-bc200-bc290",
    categoria: "recambios",
    nombre: "Bomba enfriador BC200 / BC290",
    resumen: "Recambio de bomba de agua para los enfriadores evaporativos BC200 y BC290.",
    imagen: null,
    pvp: 59.9,
    sageTools: "1019001",
    gid: "5176.15",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el circuito de agua de los enfriadores evaporativos BC200 y BC290.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "bomba-bc395",
    categoria: "recambios",
    nombre: "Bomba enfriador BC395",
    resumen: "Recambio de bomba de agua para el enfriador evaporativo BC395.",
    imagen: null,
    pvp: 72.25,
    sageTools: "1019002",
    gid: "5176.14",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el circuito de agua del enfriador evaporativo BC395.",
    specs: [
      { label: "Compatible con", value: "BC395" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "filtros-bc200",
    categoria: "recambios",
    nombre: "Paquete de filtros BC200 (3 uds.)",
    resumen: "Recambio de filtros para el enfriador evaporativo BC200.",
    imagen: null,
    pvp: 93.25,
    sageTools: "1018001",
    gid: "5176.18",
    destacado: false,
    descripcion: "Paquete de 3 filtros de recambio originales Blizzcool para el enfriador evaporativo BC200.",
    specs: [
      { label: "Compatible con", value: "BC200" },
      { label: "Unidades", value: "3" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "filtros-bc290",
    categoria: "recambios",
    nombre: "Paquete de filtros BC290 (3 uds.)",
    resumen: "Recambio de filtros para el enfriador evaporativo BC290.",
    imagen: null,
    pvp: 104,
    sageTools: "1018002",
    gid: "5176.12",
    destacado: false,
    descripcion: "Paquete de 3 filtros de recambio originales Blizzcool para el enfriador evaporativo BC290.",
    specs: [
      { label: "Compatible con", value: "BC290" },
      { label: "Unidades", value: "3" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "filtros-bc395",
    categoria: "recambios",
    nombre: "Paquete de filtros BC395 (3 uds.)",
    resumen: "Recambio de filtros para el enfriador evaporativo BC395.",
    imagen: null,
    pvp: 147.35,
    sageTools: "1018003",
    gid: "5176.13",
    destacado: false,
    descripcion: "Paquete de 3 filtros de recambio originales Blizzcool para el enfriador evaporativo BC395.",
    specs: [
      { label: "Compatible con", value: "BC395" },
      { label: "Unidades", value: "3" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "generador-anion",
    categoria: "recambios",
    nombre: "Generador de anión",
    resumen: "Recambio del generador de aniones para enfriadores evaporativos Blizzcool.",
    imagen: null,
    pvp: 59.9,
    sageTools: "1019010",
    gid: "5176.16",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el sistema de generación de aniones incorporado en los enfriadores evaporativos.",
    specs: [
      { label: "Tipo", value: "Recambio — generador de aniones" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "panel-control-bc",
    categoria: "recambios",
    nombre: "Panel de control BC200 / BC290 / BC395",
    resumen: "Recambio de panel de control para toda la gama de enfriadores BC.",
    imagen: null,
    pvp: 59.95,
    sageTools: "1019003",
    gid: "5176.23",
    destacado: false,
    descripcion: "Panel de control de recambio original Blizzcool, compatible con los tres modelos de la gama de enfriadores evaporativos BC.",
    specs: [
      { label: "Compatible con", value: "BC200, BC290, BC395" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "helice-bc200",
    categoria: "recambios",
    nombre: "Hélice enfriador BC200",
    resumen: "Recambio de hélice para el enfriador evaporativo BC200.",
    imagen: null,
    pvp: 28.5,
    sageTools: "1019004",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC200.",
    specs: [
      { label: "Compatible con", value: "BC200" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "helice-bc290",
    categoria: "recambios",
    nombre: "Hélice enfriador BC290",
    resumen: "Recambio de hélice para el enfriador evaporativo BC290.",
    imagen: null,
    pvp: 56.35,
    sageTools: "1019005",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC290.",
    specs: [
      { label: "Compatible con", value: "BC290" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "helice-bc395",
    categoria: "recambios",
    nombre: "Hélice enfriador BC395",
    resumen: "Recambio de hélice para el enfriador evaporativo BC395.",
    imagen: null,
    pvp: 78.48,
    sageTools: "1019006",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC395.",
    specs: [
      { label: "Compatible con", value: "BC395" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "parrilla-bc200",
    categoria: "recambios",
    nombre: "Parrilla enfriador BC200",
    resumen: "Recambio de parrilla para el enfriador evaporativo BC200.",
    imagen: null,
    pvp: 22.8,
    sageTools: "1019007",
    gid: null,
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC200.",
    specs: [
      { label: "Compatible con", value: "BC200" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "parrilla-bc290",
    categoria: "recambios",
    nombre: "Parrilla enfriador BC290",
    resumen: "Recambio de parrilla para el enfriador evaporativo BC290.",
    imagen: null,
    pvp: 40.25,
    sageTools: "1019008",
    gid: "5176.8",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC290.",
    specs: [
      { label: "Compatible con", value: "BC290" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "parrilla-bc395",
    categoria: "recambios",
    nombre: "Parrilla enfriador BC395",
    resumen: "Recambio de parrilla para el enfriador evaporativo BC395.",
    imagen: null,
    pvp: 50.49,
    sageTools: "1019009",
    gid: "5176.9",
    destacado: false,
    descripcion: "Pieza de recambio original Blizzcool para el enfriador evaporativo BC395.",
    specs: [
      { label: "Compatible con", value: "BC395" },
    ],
    aplicaciones: [],
    variantes: null,
  },
  {
    id: "pack-pc01",
    categoria: "recambios",
    nombre: "Pack refrigerante PC01 (4 uds.)",
    resumen: "Pack de 4 placas refrigerantes de recambio para chalecos PCM.",
    imagen: null,
    pvp: 109.9,
    sageTools: "1090051",
    gid: "5287.3",
    destacado: false,
    descripcion: "Pack de 4 placas PCM de recambio, compatibles con los chalecos refrigerantes PCM de la gama Blizzcool, para disponer de juegos extra y alternar ciclos sin interrumpir el turno.",
    specs: [
      { label: "Unidades", value: "4" },
      { label: "Compatible con", value: "Chalecos refrigerantes PCM Blizzcool" },
    ],
    aplicaciones: [],
    variantes: null,
  },
];
